### ISSUE TITLE
Icon request: Generic server

### ISSUE THREAD

**Issue by benwaffle** [aegis-icons/aegis-icons#10]
I have a couple 2FA codes for some servers that I ssh into. It would be nice to have a generic server icon.

(Also, sorry for filing so many issues)

**Comment by krisu5** [comment]
Yeah, I had idea to make generic icons too. Most likely gonna use some icon pack for these, but not sure which one. Maybe material icons?

It's fine, it's better to have all of the issues separately.

**Comment by krisu5** [comment]
Here's the server icon. Hope that it satifies your needs :)

https://github.com/krisu5/aegis-icons/blob/master/PNG/Generic%20Icons/Server.png
