### ISSUE TITLE
Icon request: Netlify

### ISSUE THREAD

**Issue by pdhoopr** [aegis-icons/aegis-icons#100]
- URL of the site or app **(required):**  https://www.netlify.com
- Logo resources for the icon **(optional, but recommended):** https://www.netlify.com/press/#logos

**Comment by krisu5** [comment]
Here you go!

https://github.com/krisu5/aegis-icons/blob/master/PNG/Netlify.png

**Comment by pdhoopr** [comment]
Perfect, thank you!!
