### ISSUE TITLE
Icon request: Betterment

### ISSUE THREAD

**Issue by brandonaut** [aegis-icons/aegis-icons#101]
- URL of the site or app **(required):** https://www.betterment.com/
- Logo resources for the icon **(optional, but recommended):** https://www.betterment.com/press/

**Comment by krisu5** [comment]
Here you go!

https://github.com/krisu5/aegis-icons/blob/master/PNG/Betterment.png
https://github.com/krisu5/aegis-icons/blob/master/PNG/Variations/Betterment%20bg.var.png
