### ISSUE TITLE
Icon request: Intuit

### ISSUE THREAD

**Issue by A37stKpDodi4BEr65TXb** [aegis-icons/aegis-icons#102]
- URL of the site or app **(required):** https://www.intuit.com
- Logo resources for the icon **(optional, but recommended):** 
https://www.intuit.com/company/press-room/logos/
https://www.mint.com/sites/default/files/intuit_logo_link_presspg.png
https://www.mint.com/sites/default/files/mintlogo_link_presspg.png
https://blog.turbotax.intuit.com/wp-content/uploads/2017/02/tt_logo_horz_endorse_rgb_pos.png
https://s3-us-west-2.amazonaws.com/designsystems-sbgde-096068918679-us-west-2/wp-content/uploads/2020/03/30135125/qb-logo.svg

Note: Intuit has several products but they share the same Intuit account. I'm not sure which way would be easier. Three separate icons or just one.

**Comment by krisu5** [comment]
Since they are all using same account, I rather just make Intuit icon.

https://github.com/krisu5/aegis-icons/blob/master/PNG/Intuit.png
