### ISSUE TITLE
Icon request: Uptime Robot

### ISSUE THREAD

**Issue by m-p-3** [aegis-icons/aegis-icons#104]
- URL of the site or app **(required):** https://uptimerobot.com/
- Logo resources for the icon **(optional, but recommended):** https://lh3.googleusercontent.com/7chgAWpHyGiU4tYisissVa5sMeC4iDHl1fh1aAKaGxzs5q2Es_8EtWm9hpYB00-upg=s512

**Comment by krisu5** [comment]
Here you go!

https://github.com/krisu5/aegis-icons/blob/master/PNG/UptimeRobot.png
