### ISSUE TITLE
Icon request: Nexus Mods

### ISSUE THREAD

**Issue by Leilukin** [aegis-icons/aegis-icons#106]
- URL of the site or app **(required):** https://www.nexusmods.com/
- Logo resources for the icon **(optional, but recommended):** https://nitter.net/pic/profile_images%2F1134447198022852609%2FWzoqA2vi_400x400.png

**Comment by krisu5** [comment]
Here you go!

https://github.com/krisu5/aegis-icons/blob/master/PNG/Nexus%20Mods.png
