### ISSUE TITLE
Icon request: Citra Emulator (forum)

### ISSUE THREAD

**Issue by cirump** [aegis-icons/aegis-icons#108]
- URL of the site or app **(required):**  citra-emu.org
- Logo resources for the icon **(optional, but recommended):**

**Comment by krisu5** [comment]
Not a service with 2FA support, to my knowledge.

**Comment by cirump** [comment]
Yes it has 2FA 

Who said it doesn't?

I have it enabled rn!

Why would i ask for it if i hadn't enabled it

**Comment by krisu5** [comment]
I just didn't find anything related to 2FA and Citra emulator with Google search. I don't understand why would emulator use / need 2FA imo.

Is it related to [Citra Web Service](https://citra-emu.org/wiki/citra-web-service/) feature? If it is, then okay fine. I reopen the issue then for now.

If it's related to the **forums**, then use one of the Discource icons (forums are powered with that).

Vector logo: https://github.com/citra-emu/citra-assets/blob/master/Main/citra_logo.svg

**Comment by cirump** [comment]
Sorry about that I didn't read the instructions.

Yes it for the fourms!!!!

so you use discourse logo for forums interesting

**Comment by krisu5** [comment]
Alrightie then :)

Note to self: this issue is linked to #94
