### ISSUE TITLE
Icon request: Glassdoor

### ISSUE THREAD

**Issue by A37stKpDodi4BEr65TXb** [aegis-icons/aegis-icons#109]
- URL of the site or app **(required):** https://www.glassdoor.com/
- Logo resources for the icon **(optional, but recommended):** https://www.glassdoor.com/about-us/press/media-assets/

**Comment by krisu5** [comment]
Here you go!

https://github.com/krisu5/aegis-icons/blob/master/PNG/Glassdoor.png
