### ISSUE TITLE
Icon request: Ubisoft

### ISSUE THREAD

**Issue by rahulkalluri** [aegis-icons/aegis-icons#114]
- URL of the site or app **(required):** https://www.ubisoft.com
- Logo resources for the icon **(optional, but recommended):** https://ubistatic-a.akamaihd.net/0090/PROD/ubigroup/PressKit/Logo_EN.zip

**Comment by krisu5** [comment]
Ubisoft already exists.

https://github.com/aegis-icons/aegis-icons/blob/master/PNG/Ubisoft.png
https://github.com/aegis-icons/aegis-icons/blob/master/PNG/Variations/Ubisoft%20bg.var.png
