### ISSUE TITLE
Icon request: Lichess

### ISSUE THREAD

**Issue by rahulkalluri** [aegis-icons/aegis-icons#116]
- URL of the site or app **(required):** https://lichess.org/
- Logo resources for the icon **(optional, but recommended):** https://lichess.cdn.prismic.io/lichess/1599c13f-65c0-432d-8545-511cd8f5b0bd_Press+Kit+2020+Images.zip

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/PNG/Lichess.png
https://github.com/aegis-icons/aegis-icons/blob/master/PNG/Variations/Lichess%20bg.var.png
https://github.com/aegis-icons/aegis-icons/blob/master/PNG/Variations/Lichess%20fg.bg.var.png
