### ISSUE TITLE
Icon request: NotABug.org

### ISSUE THREAD

**Issue by Kelvino9** [aegis-icons/aegis-icons#120]
- URL of the site or app **(required):** https://notabug.org/
- Logo resources for the icon **(optional, but recommended):** https://notabug.org/img/notabug-lg.png

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/PNG/NotABug.org.png
https://github.com/aegis-icons/aegis-icons/blob/master/PNG/Variations/NotABug.org%20bg.var.png

**Comment by Kelvino9** [comment]
Thank you so much for creating all of the requested icons. They are great.
