### ISSUE TITLE
Icon request: mail.de

### ISSUE THREAD

**Issue by Kelvino9** [aegis-icons/aegis-icons#121]
- URL of the site or app **(required):** https://mail.de/
- Logo resources for the icon **(optional, but recommended):** https://mail.de/img/logo_blackMailBlue.png

**Comment by krisu5** [comment]
Better resolution / quality: https://de.wikipedia.org/wiki/Datei:Mail.de.png

**Comment by Kelvino9** [comment]
Sure, that looks clearer.

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/PNG/mail.de.png
