### ISSUE TITLE
Icon request: ZeroTier

### ISSUE THREAD

**Issue by CrabAss** [aegis-icons/aegis-icons#123]
- URL of the site or app **(required):** https://www.zerotier.com/
- Logo resources for the icon **(optional, but recommended):** https://en.wikipedia.org/wiki/File:ZeroTier_Logo.png

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/PNG/ZeroTier.png
https://github.com/aegis-icons/aegis-icons/blob/master/PNG/Variations/ZeroTier%20bg.var.png
