### ISSUE TITLE
Icon request: Linode

### ISSUE THREAD

**Issue by CrabAss** [aegis-icons/aegis-icons#124]
- URL of the site or app **(required):** https://www.linode.com/
- Logo resources for the icon **(optional, but recommended):** https://www.linode.com/wp-content/uploads/2018/10/linode-logo-blk-rgb-minified.svg

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/PNG/Linode.png

**Comment by CrabAss** [comment]
Thank you so much for making these beautiful icons!
