### ISSUE TITLE
Icon request: Pypi (Python Packages)

### ISSUE THREAD

**Issue by Findus23** [aegis-icons/aegis-icons#126]
- URL of the site or app **(required):** https://pypi.org/
- Logo resources for the icon **(optional, but recommended):** https://pypi.org/static/images/logo-small.6eef541e.svg

Alternatively using the Python logo would maybe be easier: https://commons.wikimedia.org/wiki/File:Python-logo-notext.svg

**Comment by krisu5** [comment]
Usually I go with most official logo possible, but in this case PyPI's logo is way too dense.

https://github.com/aegis-icons/aegis-icons/blob/master/PNG/Python%20Package%20Index.png
