### ISSUE TITLE
Update icon: microsoft.com

### ISSUE THREAD

**Issue by kongo09** [aegis-icons/aegis-icons#130]
The Microsoft icon does not show the correct coloring.

Please see here: https://www.microsoft.com/en-us/legal/intellectualproperty/trademarks/usage/logo.aspx

**Comment by krisu5** [comment]
It's slightly off, but not much. Original color is taken from Simple Icons and it's based of logotype's coloring.

I update it based of Wikipedia's vector and it's logotype, it seems to be closest to official (you need to contact Microsoft for official media kit, I think that's waste of time)
https://commons.wikimedia.org/wiki/File:Microsoft_logo_(2012).svg

**Comment by krisu5** [comment]
Icon updated:

https://github.com/aegis-icons/aegis-icons/blob/master/PNG/Microsoft.png
