### ISSUE TITLE
Icon request: nuki.io

### ISSUE THREAD

**Issue by kongo09** [aegis-icons/aegis-icons#131]
- App: https://play.google.com/store/apps/details?id=io.nuki

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/PNG/Nuki.png
https://github.com/aegis-icons/aegis-icons/blob/master/PNG/Variations/Nuki%20fg.var.png

**Comment by kongo09** [comment]
Thanks. However, I would recommend to the Nuki signature color of black (all their devices and logos are black) and rather use their circle logo as they do for the app.

https://lh3.googleusercontent.com/nyLOGY9wjGdHrh0Zd1yq1CU-gkp4ldNvvVIkHnyTn0UDw0NlFkILeH8P47SHVPb_FFnS=s180-rw

**Comment by krisu5** [comment]
Here's _unofficial_ icon for circle logo, this is not gonna be submitted to the icon pack. Here's why.

1. I try to avoid really generic icons as much as possible, there's billion logos with just a circle (there's multiple apps / sites in the icon pack that has secondary "circle logo" also). It's not distinct enough, imo.
2. Based of the website and branding, it's not their main logo. It's not in the [press kit](https://nuki.io/en/press/). It's alternative logo for social media, app icons and favicon.
3. Main logo doesn't take that much space, so it's still relatively easy to notice and read even in small size.

![Nuki unofficial](https://user-images.githubusercontent.com/3540275/95848677-0ad55100-0d57-11eb-922b-2ad1fa742391.png)

I agree with black color as more common brand color, I make another black one with main logo and make that as main icon and others as variations / alternatives.

EDIT: final official icons

https://github.com/aegis-icons/aegis-icons/blob/master/PNG/Nuki.png
https://github.com/aegis-icons/aegis-icons/blob/master/PNG/Variations/Nuki%20bg.fg.var.png
https://github.com/aegis-icons/aegis-icons/blob/master/PNG/Variations/Nuki%20bg.var.png

**Comment by kongo09** [comment]
Highly appreciated, thanks.
