### ISSUE TITLE
Update icon: xing.com

### ISSUE THREAD

**Issue by kongo09** [aegis-icons/aegis-icons#134]
The logo coloring is wrong. You should use white background with the two greens:

- App: https://play.google.com/store/apps/details?id=com.xing.android

**Comment by krisu5** [comment]
We never use white as background color (as stated in CONTRIBUTING.md). White is only used as foreground (eg. logo) color.

I'm pretty sure the background color is one of the green ones, but I double-check that later.

**Comment by krisu5** [comment]
Yup, background color is correct. It's taken from official vector logo and it's darker green one (`#006567`).

No updates needed.
