### ISSUE TITLE
Icon request: codeship.com

### ISSUE THREAD

**Issue by adamhl8** [aegis-icons/aegis-icons#135]
- URL of the site or app **(required):** [https://codeship.com](https://codeship.com)
- Logo resources for the icon **(optional, but recommended):** [Here is the SVG](https://github.com/aegis-icons/aegis-icons/files/5379211/codeship.zip) I pulled from: [https://app.codeship.com/registrations/new](https://app.codeship.com/registrations/new)

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/PNG/CodeShip.png
