### ISSUE TITLE
Icon request: HMRC (gov.uk)

### ISSUE THREAD

**Issue by pnsantos** [aegis-icons/aegis-icons#136]
- URL of the site or app **(required):** https://play.google.com/store/apps/details?id=uk.gov.hmrc.ptcalc
- Logo resources for the icon **(optional, but recommended):** https://finn-geotherm.co.uk/wp-content/uploads/2019/11/HMRC-logo.png

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/PNG/HM%20Revenue%20&%20Customs.png
