### ISSUE TITLE
Icon request: PlayStation

### ISSUE THREAD

**Issue by m-p-3** [aegis-icons/aegis-icons#137]
- URL of the site or app **(required):** https://www.playstation.com
- Logo resources for the icon **(optional, but recommended):** https://upload.wikimedia.org/wikipedia/commons/5/5c/PlayStation_logo_and_wordmark.svg

For those unaware, it's now possible to setup your PSN 2FA with a TOTP instead of text messages.
http://idp.sn/security

If you already used SMS 2FA, you'll have to disable it and re-enable it to switch.

**Comment by krisu5** [comment]
Nice news 😀

As always:
https://github.com/aegis-icons/aegis-icons/blob/master/PNG/PlayStation.png
