### ISSUE TITLE
Icon request: VirusTotal

### ISSUE THREAD

**Issue by u8Jj3** [aegis-icons/aegis-icons#138]
- URL of the site or app **(required):** https://www.virustotal.com
- Logo resources for the icon **(optional, but recommended):** https://upload.wikimedia.org/wikipedia/commons/b/b7/VirusTotal_logo.svg

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/PNG/VirusTotal.png
