### ISSUE TITLE
Icon request: PIEE (Procurement Integrated Enterprise Environment)

### ISSUE THREAD

**Issue by nichu42** [aegis-icons/aegis-icons#142]
- URL of the site or app **(required):** https://piee.eb.mil/
- Logo resources for the icon **(optional, but recommended):** https://piee.eb.mil/piee-landing/assets/images/logos/dla-piee-logo.svg

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/PNG/PIEE.png
