### ISSUE TITLE
Icon request: VRChat

### ISSUE THREAD

**Issue by Scrumplex** [aegis-icons/aegis-icons#145]
- URL of the site or app **(required):** https://hello.vrchat.com/
- Logo resources for the icon **(optional, but recommended):** https://commons.wikimedia.org/wiki/File:Vrchatlogo.png  https://seeklogo.com/vector-logo/332240/vr-chat

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/PNG/VRChat.png
https://github.com/aegis-icons/aegis-icons/blob/master/PNG/Variations/VRChat%20bg.var.png
