### ISSUE TITLE
Icon request: BorgBase

### ISSUE THREAD

**Issue by Scrumplex** [aegis-icons/aegis-icons#146]
- URL of the site or app **(required):** https://www.borgbase.com/
- Logo resources for the icon **(optional, but recommended):** 

---

I couldn't find the logo in a usable format (the website uses an icon embedded in a webfont). Maybe the provider could provide an SVG when contacted.

**Comment by krisu5** [comment]
> I couldn't find the logo in a usable format (the website uses an icon embedded in a webfont). Maybe the provider could provide an SVG when contacted.

No need to :) Logo is just [HDD icon from Font Awesome 5 iconfont.](https://fontawesome.com/icons/hdd?style=solid)

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/PNG/BorgBase.png
