### ISSUE TITLE
Icon request: sourcehut

### ISSUE THREAD

**Issue by Scrumplex** [aegis-icons/aegis-icons#147]
- URL of the site or app **(required):** https://sr.ht/
- Logo resources for the icon **(optional, but recommended):** https://sr.ht/ (SVG embedded in HTML at path `html body nav.container.navbar.navbar-light.navbar-expand-sm span.navbar-brand span.icon.icon-circle svg`)

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/PNG/sourcehut.png
https://github.com/aegis-icons/aegis-icons/blob/master/PNG/Variations/sourcehut%20bg.var.png
