### ISSUE TITLE
Icon request: Stake

### ISSUE THREAD

**Issue by Yihao-G** [aegis-icons/aegis-icons#149]
- URL of the site or app **(required):** https://hellostake.com/
- Logo resources for the icon **(optional, but recommended):** 
  - https://s3.ap-southeast-2.amazonaws.com/hellostake.com-cdn/wp-content/uploads/sites/2/2020/04/29014601/Stake_Wordmark_Black_RGB_HR.png
  - https://hellostake.com/au/wp-content/uploads/sites/2/2019/08/group-2-copy@3x.png

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/PNG/Stake.png
https://github.com/aegis-icons/aegis-icons/blob/master/PNG/Variations/Stake%20bg.var.png
