### ISSUE TITLE
Icon request: Wealthfront

### ISSUE THREAD

**Issue by Daniel15** [aegis-icons/aegis-icons#150]
- URL of the site or app **(required):**  https://www.wealthfront.com/
- Logo resources for the icon **(optional, but recommended):** 
  - SVG: https://commons.wikimedia.org/wiki/File:Wealthfront_Logo.svg

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/PNG/Wealthfront.png
