### ISSUE TITLE
Icon request: Razer / XDA Developers / Google (Suggestion)

### ISSUE THREAD

**Issue by giwrgosmant** [aegis-icons/aegis-icons#152]
Razer Icon

- URL of the site or app **(required):** https://www.razer.com/
- Logo resources for the icon **(optional, but recommended):** I guess[ this](https://icons8.com/icon/65230/razer) in black background 

**XDA Developers Icon**
- URL of the site or app (required): Site:[Here](https://www.xda-developers.com/) App:[Here](https://play.google.com/store/apps/details?id=com.xda.labs.play&hl=el&gl=US)
- Logo resources for the icon (optional, but recommended): I don't have resources but it would be nice if you could use the logo [of xda app in playstore](https://play.google.com/store/apps/details?id=com.xda.labs.play&hl=el&gl=US)

**Suggestion about Google Logo**
I think it would match better if you could use [this logo](https://www.flaticon.com/free-icon/google_2702602?term=google%20logo&page=1&position=1) in white background for Google.

**Comment by krisu5** [comment]
**Razer**
https://github.com/aegis-icons/aegis-icons/blob/master/PNG/Razer.png

**XDA-Developers**
https://github.com/aegis-icons/aegis-icons/blob/master/PNG/XDA-Developers.png

**Google**
Sorry, but in our guidelines [we don't use white as background color](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#colors). White is always color preserved for logo. Also, this logo is not [official "G" symbol](https://madeby.google.com/static/images/google_g_logo.svg).
