### ISSUE TITLE
Icon request: MercadoLibre

### ISSUE THREAD

**Issue by m0yP** [aegis-icons/aegis-icons#154]
- URL of the site or app **(required):** http://mercadolibre.com/
- Logo resources for the icon **(optional, but recommended):**

**Comment by krisu5** [comment]
Already exists:
https://github.com/aegis-icons/aegis-icons/blob/master/PNG/MercadoLibre.png
https://github.com/aegis-icons/aegis-icons/blob/master/PNG/Variations/MercadoLibre%20fg.var.png

**Comment by m0yP** [comment]
Ohh, thanks! Didn't come in latest release, though.

**Comment by krisu5** [comment]
I don't make packs often (at least not now), so if something is missing, you should check [PNG directory](https://github.com/aegis-icons/aegis-icons/tree/master/PNG) first.
