### ISSUE TITLE
Icon request: Uberspace

### ISSUE THREAD

**Issue by max-schmidt** [aegis-icons/aegis-icons#156]
- URL of the site or app **(required):** https://uberspace.de/
- Logo resources for the icon **(optional, but recommended):** https://uberspace.de/img/logo.svg

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/PNG/Uberspace.png
https://github.com/aegis-icons/aegis-icons/blob/master/PNG/Variations/Uberspace%20bg.var.png
