### ISSUE TITLE
Icon request: INWX

### ISSUE THREAD

**Issue by max-schmidt** [aegis-icons/aegis-icons#157]
- URL of the site or app **(required):** https://www.inwx.de/
- Logo resources for the icon **(optional, but recommended):** 
  - SVG: embedded at https://status.inwx.com/
  - otherwise, PNG: https://images.inwx.com/logos/inwx.png

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/PNG/INWX.png
