### ISSUE TITLE
Icon request: Plex 

### ISSUE THREAD

**Issue by unLieb** [aegis-icons/aegis-icons#158]
- URL of the site or app (required): https://www.plex.tv
- Logo resources for the icon (optional, but recommended): https://www.plex.tv/wp-content/uploads/2018/01/pmp-icon-1.png

**Comment by krisu5** [comment]
Note to self: https://github.com/aegis-icons/aegis-icons/projects/1#card-50120407

**Comment by unLieb** [comment]
I didn't find them in the icon pack I downloaded 5 days ago.

**Comment by krisu5** [comment]
> I didn't find them in the icon pack I downloaded 5 days ago.

That reply wasn't for you, it was for me 😉 You're right, that icon doesn't exist.

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/PNG/Plex.png
https://github.com/aegis-icons/aegis-icons/blob/master/PNG/Variations/Plex%20bg.var.png
