### ISSUE TITLE
Icon request: Activision

### ISSUE THREAD

**Issue by u8Jj3** [aegis-icons/aegis-icons#159]
- URL of the site or app **(required):** https://www.activision.com
- Logo resources for the icon **(optional, but recommended):** https://en.wikipedia.org/wiki/Activision#/media/File:Activision.svg

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/PNG/Activision.png
https://github.com/aegis-icons/aegis-icons/blob/master/PNG/Variations/Activision%20bg.var.png
