### ISSUE TITLE
Icon request: UpCloud

### ISSUE THREAD

**Issue by hopoluicha** [aegis-icons/aegis-icons#16]
- URL of the site or app: https://upcloud.com/
- Logo resources for the icon: https://upcloud.com/wp-content/uploads/2018/11/cropped-upcloud_icon_purple-180x180.png

Can't really find a svg logo for upcloud

**Comment by krisu5** [comment]
SVG can be found from bottom of the page (inline only, means that it's not directly downloadable and has to be copied from source code).

**Comment by krisu5** [comment]
It's done!

https://github.com/krisu5/aegis-icons/blob/master/PNG/UpCloud.png
