### ISSUE TITLE
Icon request: Wargaming.net

### ISSUE THREAD

**Issue by Zalaxx** [aegis-icons/aegis-icons#160]
- URL of the site or app **(required):** https://eu.wargaming.net/en
- Logo resources for the icon **(optional, but recommended):** https://upload.wikimedia.org/wikipedia/en/f/fa/Wargaming_logo.svg

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/PNG/Wargaming.net.png
