### ISSUE TITLE
Icon request: AVM / FRITZ! 

### ISSUE THREAD

**Issue by unLieb** [aegis-icons/aegis-icons#161]
- URL of the site or app **(required): https://en.avm.de 
- Logo resources for the icon **(optional, but recommended): https://upload.wikimedia.org/wikipedia/de/6/68/Fritz!_Logo.svg

FTITZ! (Box) is the name of the product line. Therefore, I find it better to take this logo instead of the company logo.

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/PNG/FRITZ!.png
