### ISSUE TITLE
Icon request: OpenCollective & QloudData

### ISSUE THREAD

**Issue by redfire75369** [aegis-icons/aegis-icons#162]
### URL of sites and/or apps:
- OpenCollective: https://opencollective.com/
- QloudData: https://efss.qloud.my (else, Qloud: https://www.qloud.my/)

### Logo resources for the icons
- OpenCollective: https://github.com/opencollective/opencollective-frontend/blob/master/public/static/images/favicon.ico.png
- QloudData: https://efss.qloud.my/index.php/apps/theming/favicon

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/PNG/Qloud.png
https://github.com/aegis-icons/aegis-icons/blob/master/PNG/Open%20Collective.png
