### ISSUE TITLE
Icon request: Bethesda, Trading212

### ISSUE THREAD

**Issue by ciotorcristian** [aegis-icons/aegis-icons#165]
- URL of the site or app **(required):** https://bethesda.net/
- Logo resources for the icon **(optional, but recommended):** 

- URL of the site or app **(required):** https://www.trading212.com
- Logo resources for the icon **(optional, but recommended):**

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/PNG/Bethesda.png
https://github.com/aegis-icons/aegis-icons/blob/master/PNG/Variations/Bethesda%20bg.var.png
https://github.com/aegis-icons/aegis-icons/blob/master/PNG/Trading%20212.png
