### ISSUE TITLE
Icon request: Short.io

### ISSUE THREAD

**Issue by redfire75369** [aegis-icons/aegis-icons#166]
**URL of site**
- Short.io: https://short.io / https://app.short.io

**Logo resources for the icons**
- Short.io: https://short.io/favicon-32x32.png / https://app.short.io/settings/logo-square.svg

Note: I included both icons as they are slightly different. You may choose whichever you prefer.

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/PNG/Short.io.png
