### ISSUE TITLE
Icon submission: Clover

### ISSUE THREAD

**Issue by justsomemate** [aegis-icons/aegis-icons#167]
- [x] I have read and followed CONTRIBUTING document.
- URL of the site or app **(required):** https://www.clover.com/
- Logo resources for the icon:
  - https://www.clover.com/static/favicons/safari-pinned-tab.svg color="#228800"

Uploaded files:
[Clover.zip](https://github.com/aegis-icons/aegis-icons/files/6135963/Clover.zip)
![Clover](https://user-images.githubusercontent.com/80608392/111055382-f054f000-843a-11eb-9bc8-9b9139123992.png)

**Comment by krisu5** [comment]
Added to the repo 👍
