### ISSUE TITLE
Icon submission: Kaseya

### ISSUE THREAD

**Issue by justsomemate** [aegis-icons/aegis-icons#168]
- [x] I have read and followed CONTRIBUTING document.
- URL of the site or app **(required):** https://www.kaseya.com/
- Logo resources for the icon:
  - https://www.kaseya.com/brand/
  - https://www.kaseya.com (SVG embedded in source)

Uploaded files:
[Kaseya.zip](https://github.com/aegis-icons/aegis-icons/files/6135968/Kaseya.zip)
![Kaseya](https://user-images.githubusercontent.com/80608392/111055454-9b65a980-843b-11eb-80b7-4ef9d73143a4.png)

**Comment by krisu5** [comment]
Added to the repo 👍 (logo is too big, so I changed that)
