### ISSUE TITLE
Icon submission: Unitrends

### ISSUE THREAD

**Issue by justsomemate** [aegis-icons/aegis-icons#169]
- [x] I have read and followed CONTRIBUTING document.
- URL of the site or app **(required):** https://www.unitrends.com/
- Logo resources for the icon:
  - https://www.unitrends.com (SVG embedded in source)

Uploaded files:
[Unitrends.zip](https://github.com/aegis-icons/aegis-icons/files/6135969/Unitrends.zip) (includes main and bg.var)
![Unitrends](https://user-images.githubusercontent.com/80608392/111055486-e67fbc80-843b-11eb-9348-6e29a1256b16.png)
![Unitrends bg var](https://user-images.githubusercontent.com/80608392/111055487-ea134380-843b-11eb-9a6c-bab4027799bb.png)

**Comment by krisu5** [comment]
Added to the repo 👍 (logo is too big, so I changed that)
