### ISSUE TITLE
Icon request: Phabricator

### ISSUE THREAD

**Issue by hopoluicha** [aegis-icons/aegis-icons#17]
Remember to add **name of the site or app** at the end of the title (you can delete this line if you want)

- URL of the site or app: https://secure.phabricator.com/
- Logo resources for the icon: https://p.phcdn.net/file/data/@secure/7n3t3fb3ohfrnl6mu6ct/PHID-FILE-47v4pislyk67ytzd3v7e/light-eye.png

Can't find SVG

**Comment by krisu5** [comment]
Font Awesome has SVG: https://fontawesome.com/icons/phabricator?style=brands

**Comment by krisu5** [comment]
Here's the icon.

https://github.com/krisu5/aegis-icons/blob/master/PNG/Phabricator.png
