### ISSUE TITLE
Icon submission: Twilio

### ISSUE THREAD

**Issue by justsomemate** [aegis-icons/aegis-icons#170]
- [x] I have read and followed CONTRIBUTING document.
- URL of the site or app **(required):** https://www.twilio.com/
- Logo resources for the icon
  - https://www.twilio.com/company/brand
  - https://www.twilio.com/docs/static/company/img/logos/red/twilio-mark-red.0a7746436.svg

Uploaded files:
[Twilio.zip](https://github.com/aegis-icons/aegis-icons/files/6135973/Twilio.zip)
![Twilio](https://user-images.githubusercontent.com/80608392/111055519-2f377580-843c-11eb-8839-5b118642cb6a.png)

**Comment by krisu5** [comment]
Added to the repo 👍
