### ISSUE TITLE
Icon submission: Palo Alto Networks

### ISSUE THREAD

**Issue by justsomemate** [aegis-icons/aegis-icons#171]
- [x] I have read and followed CONTRIBUTING document.
- URL of the site or app **(required):** https://www.paloaltonetworks.com/
- Logo resources for the icon:
  - https://www.paloaltonetworks.com/company/brand
  - https://en.wikipedia.org/wiki/File:PaloAltoNetworks_2020_Logo.svg

Uploaded files:
[Palo Alto Networks.zip](https://github.com/aegis-icons/aegis-icons/files/6135974/Palo.Alto.Networks.zip)
![Palo Alto Networks](https://user-images.githubusercontent.com/80608392/111055572-b4bb2580-843c-11eb-9c3b-9d999c66b9b5.png)

**Comment by krisu5** [comment]
Added to the repo 👍 (logo is too big, so I changed that)
