### ISSUE TITLE
Icon request: Philips Hue

### ISSUE THREAD

**Issue by samoz83** [aegis-icons/aegis-icons#173]
- URL of the site or app **(required):** https://account.meethue.com
- Logo resources for the icon **(optional, but recommended):** https://en.wikipedia.org/wiki/Philips_Hue#/media/File:Philips_hue_logo.png

**Comment by krisu5** [comment]
I rather do icons for the main brand, if you don't mind that.

https://github.com/aegis-icons/aegis-icons/blob/master/PNG/Philips.png
https://github.com/aegis-icons/aegis-icons/blob/master/PNG/Variations/Philips%20alt.png
