### ISSUE TITLE
Icon request: Bugzilla

### ISSUE THREAD

**Issue by redfire75369** [aegis-icons/aegis-icons#174]
**URL of site**
- Bugzilla@Mozilla: https://bugzilla.mozilla.org

**Logo resources for the icon**
- Bugzilla@Mozilla: https://bugzilla.mozilla.org/extensions/BMO/web/images/favicon.ico

**Comment by krisu5** [comment]
Bugzilla is [FOSS software](https://en.wikipedia.org/wiki/Bugzilla) that's used more then one organization, so I rather make icon for the software, not specifically for Mozilla's Bugzilla site.

Logo SVG: https://commons.wikimedia.org/wiki/File:Buggie.svg

**Comment by krisu5** [comment]
Done!

https://github.com/aegis-icons/aegis-icons/blob/master/PNG/Bugzilla.png
