### ISSUE TITLE
Icon submission: BlockFi

### ISSUE THREAD

**Issue by Selovert** [aegis-icons/aegis-icons#175]
- [x] I have read and followed CONTRIBUTING document.
- URL of the site or app **(required):** https://blockfi.com/
- Logo resources for the icon:
  - SVG logo scraped from front page of blockfi.com (hardcoded into source, so can't link)

Uploaded files:
[BlockFi.zip](https://github.com/aegis-icons/aegis-icons/files/6179078/BlockFi.zip)
![BlockFi](https://user-images.githubusercontent.com/1494739/111933085-fc186600-8a7b-11eb-88c9-a1190c5d7996.png)

**Comment by krisu5** [comment]
Added to repo.
