### ISSUE TITLE
Icon submission: Fundrise

### ISSUE THREAD

**Issue by Selovert** [aegis-icons/aegis-icons#176]
- [x] I have read and followed CONTRIBUTING document.
- URL of the site or app **(required):** https://fundrise.com/
- Logo resources for the icon:
  - [Fundrise press kit logo](https://d10cq78zmnjvsx.cloudfront.net/website-documents/fundrise-logo.pdf)

Uploaded files:
[Fundrise.zip](https://github.com/aegis-icons/aegis-icons/files/6179086/Fundrise.zip)
![Fundrise](https://user-images.githubusercontent.com/1494739/111933280-5a454900-8a7c-11eb-8880-bbf92e432b84.png)

**Comment by krisu5** [comment]
Added to repo.
