### ISSUE TITLE
Icon submission: Obsidian Entertainment

### ISSUE THREAD

**Issue by Selovert** [aegis-icons/aegis-icons#177]
- [x] I have read and followed CONTRIBUTING document.
- URL of the site or app **(required):** https://eternity.obsidian.net/
- Logo resources for the icon:
  - Div class "ob__logo" on homepage

Uploaded files:
[Obsidian Entertainment.zip](https://github.com/aegis-icons/aegis-icons/files/6179095/Obsidian.Entertainment.zip)
[Obsidian Entertainment bg.var.zip](https://github.com/aegis-icons/aegis-icons/files/6179097/Obsidian.Entertainment.bg.var.zip)
![Obsidian Entertainment](https://user-images.githubusercontent.com/1494739/111933484-d049b000-8a7c-11eb-86af-e47308af3d2f.png)
![Obsidian Entertainment bg var](https://user-images.githubusercontent.com/1494739/111933500-d6d82780-8a7c-11eb-9de0-4aee06a73962.png)

**Comment by krisu5** [comment]
Added to repo.

`Obsidian Entertainment bg.var` renamed to `Obsidian Entertainment fg.bg.var` and made new `Obsidian Entertainment bg.var` with white icon.
