### ISSUE TITLE
Icon submission: SendCutSend

### ISSUE THREAD

**Issue by Selovert** [aegis-icons/aegis-icons#178]
- [x] I have read and followed CONTRIBUTING document.
- URL of the site or app **(required):** https://sendcutsend.com/
- Logo resources for the icon:
  - [SendCutSend press page](https://sendcutsend.com/newsroom/) (scroll to bottom)

Uploaded files:
[SendCutSend.zip](https://github.com/aegis-icons/aegis-icons/files/6179110/SendCutSend.zip)
![SendCutSend](https://user-images.githubusercontent.com/1494739/111933769-6251b880-8a7d-11eb-9519-b6b6757de560.png)

**Comment by krisu5** [comment]
Added to the repo.

I made logo little bit smaller.
