### ISSUE TITLE
Update icon: Yahoo

### ISSUE THREAD

**Issue by krisu5** [aegis-icons/aegis-icons#18]
Yahoo just recently updated their brand identity: https://www.pentagram.com/work/yahoo/story

**Comment by krisu5** [comment]
Here's ZIP with SVG, AI and EPS
[yahoo.zip](https://github.com/krisu5/aegis-icons/files/3647335/yahoo.zip)

**Comment by jerryn70** [comment]
@krisu5 BTW yahoo india has 2FA do you have any plan to add yahoo icon ? Or i need to open a new issue ?

**Comment by krisu5** [comment]
> @krisu5 BTW yahoo india has 2FA do you have any plan to add yahoo icon ? Or i need to open a new issue ?

No need to, I did it just now: https://github.com/aegis-icons/aegis-icons/commit/bdd2a3a8660cc47d66f3ce155d2c497b2e3eeb50
