### ISSUE TITLE
Icon submission: TaxSlayer

### ISSUE THREAD

**Issue by Selovert** [aegis-icons/aegis-icons#180]
- [x] I have read and followed CONTRIBUTING document.
- URL of the site or app **(required):** https://www.taxslayer.com/
- Logo resources for the icon:
  - [SVG logo on homepage footer](https://designvz.azureedge.net/content/images/TaxSlayer_icon.svg)

Uploaded files:
[TaxSlayer.zip](https://github.com/aegis-icons/aegis-icons/files/6179141/TaxSlayer.zip)
![TaxSlayer](https://user-images.githubusercontent.com/1494739/111934364-7cd86180-8a7e-11eb-8a0e-0fdb3a585bf8.png)

**Comment by krisu5** [comment]
Added to the repo.

I have added you to the special thanks: https://github.com/aegis-icons/aegis-icons/blob/master/CREDITS-TO-CONTRIBUTORS.md
