### ISSUE TITLE
Icon request: Joomla

### ISSUE THREAD

**Issue by Sami32** [aegis-icons/aegis-icons#183]
https://www.joomla.org/

Logos: https://drive.google.com/drive/mobile/folders/0B-WMsfRg_wivSV83SzZzZ2tRM2M?usp=sharing&usp=sharing&urp=https://drive.google.com/folderview?id%3D0B-WMsfRg_w#grid

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/PNG/Joomla.png
