### ISSUE TITLE
Icon request: Mailo

### ISSUE THREAD

**Issue by Sami32** [aegis-icons/aegis-icons#184]
https://www.mailo.com/

[logo_mailo_35.svg.txt](https://github.com/aegis-icons/aegis-icons/files/6255084/logo_mailo_35.svg.txt)
Remove the fake .txt extension of the attached logo.

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/PNG/Mailo.png
