### ISSUE TITLE
Icon request: Dismail.de

### ISSUE THREAD

**Issue by Sami32** [aegis-icons/aegis-icons#185]
https://dismail.de/

Believe or not but i'm not aware of any logo concerning this provider.

**Comment by krisu5** [comment]
There was a favicon, so I made icon based of that.

https://github.com/aegis-icons/aegis-icons/blob/master/PNG/dismail.de.png

**Comment by Sami32** [comment]
Nice finding +1

**Comment by Sami32** [comment]
But it seem that was a very old unused one...

I finally find their official logo on their social website https://social.tchncs.de/@dismail:
https://f2.tchncs.de/accounts/headers/000/091/511/original/db2309f30b9fb589.png

**Comment by krisu5** [comment]
But there's icon in the favicon and they don't have clear branding, so I'm not updating it. "Logo" in the social media doesn't cut it.

**Comment by Sami32** [comment]
No problem, it was just to inform you. Updating this one on my side is fine.

Your icons package help Aegis to reach Authy UIX in any case so i'll not complain ;)
