### ISSUE TITLE
Icon request: Celsius Network

### ISSUE THREAD

**Issue by Sami32** [aegis-icons/aegis-icons#189]
https://app.celsius.network/ (only for beta testers)
https://play.google.com/store/apps/details?id=network.celsius.wallet&hl=en_US&gl=US

https://s3-eu-west-1.amazonaws.com/tpd/logos/5cf4a7e3341abe0001a09ed9/0x0.png

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/PNG/Celsius.png

**Comment by Sami32** [comment]
Thank you very much for all your work that will greatly enhance Aegis experience!
