### ISSUE TITLE
Icon request: Nexo

### ISSUE THREAD

**Issue by Sami32** [aegis-icons/aegis-icons#195]
https://www.nexo.io/

https://github.com/nexofinance/NEXO-Token/blob/master/assets/nexo.svg

**Comment by krisu5** [comment]
The Nexo's front page is saying that Nexo brand is retired and splitted to the two companies.

Possibly "assets365" is new one?

**Comment by Sami32** [comment]
Oups...i apology for having be too fast before posting it without verifying :~
Familly was coming to eat ;)

I corrected the links above.

**Comment by krisu5** [comment]
Okay, here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/PNG/Nexo.png
