### ISSUE TITLE
Icon request: DueDEX

### ISSUE THREAD

**Issue by Sami32** [aegis-icons/aegis-icons#196]
https://www.duedex.com/

https://pbs.twimg.com/profile_images/1351203695279669251/pG3J2phQ_400x400.jpg

**Comment by krisu5** [comment]
Site doesn't load, so I'm putting this on hold for now. If there's SVG vector in the site, I rather want to use that.

**Comment by Sami32** [comment]
Weird...it load fine for me so perhaps it was just an overload when you tried to connect or your country's IP (US?) is blocked.
https://www.duedex.com/en-US/

Sorry but from my old smartphone i don't know how to look for SVG.
https://github.com/DueDEX/DueDex.NET/blob/master/Resources/DueDEX.png

**Comment by krisu5** [comment]
It seems like it was sneaky VPN block :)

https://github.com/aegis-icons/aegis-icons/blob/master/PNG/DueDEX.png
