### ISSUE TITLE
Icon request: HYGH

### ISSUE THREAD

**Issue by Sami32** [aegis-icons/aegis-icons#197]
https://hygh.tech/

https://hygh.tech/wp-content/uploads/2021/03/HYGH-logo-white.svg

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/PNG/HYGH.png
https://github.com/aegis-icons/aegis-icons/blob/master/PNG/Variations/HYGH%20bg.var.png
