### ISSUE TITLE
Icon request: BeyondTrust Remote Support

### ISSUE THREAD

**Issue by m-p-3** [aegis-icons/aegis-icons#213]
- URL of the site or app **(required):** https://www.beyondtrust.com/remote-support
- Logo resources for the icon **(optional, but recommended):** 
![beyondtrust-remote-support](https://user-images.githubusercontent.com/3731432/114227126-90bb0900-9942-11eb-88aa-e00904617359.png)

**Comment by krisu5** [comment]
I rather make icon out of main brand if you don't mind.

https://github.com/aegis-icons/aegis-icons/blob/master/PNG/BeyondTrust.png
