### ISSUE TITLE
Icon request: Apigee

### ISSUE THREAD

**Issue by alexbakker** [aegis-icons/aegis-icons#214]
- URL of the site or app **(required):** https://cloud.google.com/apigee/
- Logo resources for the icon **(optional, but recommended):** https://commons.wikimedia.org/wiki/File:Apigee_logo.svg

**Comment by krisu5** [comment]
Here you go!

**For current Aegis** (recommended for now):
https://github.com/aegis-icons/aegis-icons/blob/master/PNG/Apigee.png

**For [Aegis beta version](https://github.com/beemdevelopment/Aegis/releases/tag/v2.0-beta1):**
https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Apigee.svg
