### ISSUE TITLE
Icon request: OneProvider

### ISSUE THREAD

**Issue by alexbakker** [aegis-icons/aegis-icons#215]
- URL of the site or app **(required):** https://oneprovider.com/
- Logo resources for the icon **(optional, but recommended):** https://prod-static.onecache.com/themes/custom/onetheme/img/oneprovider-invert.svg

**Comment by krisu5** [comment]
Here you go!

**For current Aegis** (recommended for now):
https://github.com/aegis-icons/aegis-icons/blob/master/PNG/OneProvider.png

**For [Aegis beta version](https://github.com/beemdevelopment/Aegis/releases/tag/v2.0-beta1):**
https://github.com/aegis-icons/aegis-icons/blob/master/SVG/OneProvider.svg
