### ISSUE TITLE
Icon request: Poloniex

### ISSUE THREAD

**Issue by alexbakker** [aegis-icons/aegis-icons#216]
- URL of the site or app **(required):** https://poloniex.com/
- Logo resources for the icon **(optional, but recommended):** SVG seems embedded in the home page (top left icon)

**Comment by krisu5** [comment]
Here you go!

**For current Aegis** (recommended for now):
https://github.com/aegis-icons/aegis-icons/blob/master/PNG/Poloniex.png

**For [Aegis beta version](https://github.com/beemdevelopment/Aegis/releases/tag/v2.0-beta1):**
https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Poloniex.svg

**Comment by krisu5** [comment]
Here you go!

**For current Aegis** (recommended for now):
https://github.com/aegis-icons/aegis-icons/blob/master/PNG/Poloniex.png

**For [Aegis beta version](https://github.com/beemdevelopment/Aegis/releases/tag/v2.0-beta1):**
https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Poloniex.svg
