### ISSUE TITLE
Icon request: Thycotic

### ISSUE THREAD

**Issue by alexbakker** [aegis-icons/aegis-icons#218]
- URL of the site or app **(required):** https://thycotic.com/
- Logo resources for the icon **(optional, but recommended):** Doesn't seem very official, but: https://iconape.com/thycotic-logo-logo-icon-svg-png.html.

**Comment by krisu5** [comment]
Here you go!

**For current Aegis** (recommended for now):
https://github.com/aegis-icons/aegis-icons/blob/master/PNG/Thycotic.png

**For [Aegis beta version](https://github.com/beemdevelopment/Aegis/releases/tag/v2.0-beta1):**
https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Thycotic.svg
