### ISSUE TITLE
Icon request: Versio

### ISSUE THREAD

**Issue by alexbakker** [aegis-icons/aegis-icons#219]
- URL of the site or app **(required):** https://www.versio.nl/
- Logo resources for the icon **(optional, but recommended):** I was unable to find an SVG icon for this one, unfortunately. There's a PNG icon at the top left of the home page though.

**Comment by krisu5** [comment]
Once more!

**For current Aegis** (recommended for now):
https://github.com/aegis-icons/aegis-icons/blob/master/PNG/Versio.png

**For [Aegis beta version](https://github.com/beemdevelopment/Aegis/releases/tag/v2.0-beta1):**
https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Versio.svg
