### ISSUE TITLE
Update icon: Facebook

### ISSUE THREAD

**Issue by tERyceNzAchE** [aegis-icons/aegis-icons#220]
- URL of the site or app **(required):** https://www.facebook.com/
- Logo resources for the icon **(optional, but recommended):** https://en.facebookbrand.com/facebookapp/assets/f-logo?audience=landing

Facebook's brand has changed to the more vibrant blue logo quite a while ago (2019), the icon should be updated to reflect this.

**Comment by krisu5** [comment]
Fixed!

**For current Aegis** (recommended for now):
https://github.com/aegis-icons/aegis-icons/blob/master/PNG/Facebook%20v2.png

**For [Aegis beta version](https://github.com/beemdevelopment/Aegis/releases/tag/v2.0-beta1):**
https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Facebook%20v2.svg
