### ISSUE TITLE
Icon request: NiceHash

### ISSUE THREAD

**Issue by adamhl8** [aegis-icons/aegis-icons#221]
- URL of the site or app **(required):** https://www.nicehash.com/
- Logo resources for the icon **(optional, but recommended):** https://www.nicehash.com/media

**Comment by krisu5** [comment]
Here you go!

**For current Aegis** (recommended for now):
https://github.com/aegis-icons/aegis-icons/blob/master/PNG/NiceHash.png

**For [Aegis beta version](https://github.com/beemdevelopment/Aegis/releases/tag/v2.0-beta1):**
https://github.com/aegis-icons/aegis-icons/blob/master/SVG/NiceHash.svg
