### ISSUE TITLE
Icon request: MongoDB

### ISSUE THREAD

**Issue by Raul6469** [aegis-icons/aegis-icons#222]
- URL of the site or app **(required):** https://www.mongodb.com
- Logo resources for the icon **(optional, but recommended):** https://company-30077.frontify.com/d/ghqwg6pjpJrq/mongodb-identity#/basics/logo/logo-downloads-rgb

Thank you! ✨

**Comment by krisu5** [comment]
Here you go!

**For current Aegis** (recommended for now):
https://github.com/aegis-icons/aegis-icons/blob/master/PNG/MongoDB.png

**For [Aegis beta version](https://github.com/beemdevelopment/Aegis/releases/tag/v2.0-beta1):**
https://github.com/aegis-icons/aegis-icons/blob/master/SVG/MongoDB.svg

**Comment by Raul6469** [comment]
Wow, that was fast, thank you @krisu5 !
