### ISSUE TITLE
Icon submission: Avast

### ISSUE THREAD

**Issue by maxlysenko** [aegis-icons/aegis-icons#223]
- [x] I have read and followed CONTRIBUTING document.
- URL of the site or app **(required):** https://www.avast.com/
- Where did you took the BG color(s) **(required, unless it's generic icon):** https://static3.avast.com/20001312/web/i/v2/components/logos/avast-logo-default.svg, https://press.avast.com/hubfs/media-materials/logos-guidelines/Avast/avast-logo.zip

Uploaded files:
[Avast.zip](https://github.com/aegis-icons/aegis-icons/files/6353455/Avast.zip)

![Avast](https://user-images.githubusercontent.com/12494082/115613028-96c2c980-a2f4-11eb-877a-fe0467e5b691.png)

**Comment by krisu5** [comment]
Added to the repo 👍
