### ISSUE TITLE
Icon submission: RealVNC

### ISSUE THREAD

**Issue by maxlysenko** [aegis-icons/aegis-icons#224]
- [x] I have read and followed CONTRIBUTING document.
- URL of the site or app **(required):** https://www.realvnc.com/
- Where did you took the BG color(s) **(required, unless it's generic icon):** https://static.realvnc.com/static/083142001/img/logos/realvnc.svg

Uploaded files:
[RealVNC.zip](https://github.com/aegis-icons/aegis-icons/files/6353466/RealVNC.zip)

![RealVNC](https://user-images.githubusercontent.com/12494082/115613144-b9ed7900-a2f4-11eb-9404-bc00d9d14530.png)

**Comment by krisu5** [comment]
Added to the repo 👍 
(had to make logo bit smaller)
