### ISSUE TITLE
Icon submission: SAP

### ISSUE THREAD

**Issue by maxlysenko** [aegis-icons/aegis-icons#225]
- [x] I have read and followed CONTRIBUTING document.
- URL of the site or app **(required):** https://www.sap.com/
- Where did you took the BG color(s) **(required, unless it's generic icon):** https://www.sap.com/content/dam/application/shared/logos/sap-logo-svg.svg

Uploaded files:
[SAP.zip](https://github.com/aegis-icons/aegis-icons/files/6353489/SAP.zip)

![SAP](https://user-images.githubusercontent.com/12494082/115613230-d25d9380-a2f4-11eb-9082-0de47de7b3bc.png)

**Comment by krisu5** [comment]
Added to the repo 👍 
(had to reposition logo and make it bit smaller)
