### ISSUE TITLE
Icon submission: Keenetic

### ISSUE THREAD

**Issue by maxlysenko** [aegis-icons/aegis-icons#226]
- [x] I have read and followed CONTRIBUTING document.
- URL of the site or app **(required):** https://keenetic.com/global
- Where did you took the BG color(s) **(required, unless it's generic icon):** https://keenetic.com/static/img/favicon.ico, https://keenetic.com/global

Uploaded files:
[Keenetic.zip](https://github.com/aegis-icons/aegis-icons/files/6353501/Keenetic.zip)

![Keenetic](https://user-images.githubusercontent.com/12494082/115613334-f28d5280-a2f4-11eb-957c-7afa6f6f2d74.png)

**Comment by krisu5** [comment]
Added to the repo 👍 

Name added to the credits: https://github.com/aegis-icons/aegis-icons/blob/master/CREDITS-TO-CONTRIBUTORS.md
