### ISSUE TITLE
Icon request: Forward Email

### ISSUE THREAD

**Issue by IzumiSenaSora** [aegis-icons/aegis-icons#228]
- URL of the site or app **(required):** https://forwardemail.net/en
- Logo resources for the icon **(optional, but recommended):** https://github.com/forwardemail/forwardemail.net/blob/master/assets/img/logo-square.svg

**Comment by krisu5** [comment]
Here you go!

**For current Aegis** (recommended for now):
https://github.com/aegis-icons/aegis-icons/blob/master/PNG/Forward%20Email.png

**For [Aegis beta version](https://github.com/beemdevelopment/Aegis/releases/tag/v2.0-beta1):**
https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Forward%20Email.svg
