### ISSUE TITLE
Generic icon request: Notes

### ISSUE THREAD

**Issue by IzumiSenaSora** [aegis-icons/aegis-icons#229]
I would like to request a generic icon for "Notes" Related services. My suggestion for the icon would be something like this: https://fontawesome.com/icons/sticky-note?style=regular

**Comment by krisu5** [comment]
Done (we use specific [icon libraries](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#generic-icons) for generic icons).

**For current Aegis** (recommended for now):
https://github.com/aegis-icons/aegis-icons/blob/master/PNG/Generic/Note.png

**For [Aegis beta version](https://github.com/beemdevelopment/Aegis/releases/tag/v2.0-beta1):**
https://github.com/aegis-icons/aegis-icons/blob/master/SVG/.Generic/Note.svg
