### ISSUE TITLE
Icon request: Hurricane Electric Internet Service

### ISSUE THREAD

**Issue by IzumiSenaSora** [aegis-icons/aegis-icons#230]
- URL of the site or app **(required):** https://he.net/
- Logo resources for the icon **(optional, but recommended):** https://pbs.twimg.com/profile_images/348659971/HurricaneElectric-Logo-001_-_med.png

**Comment by krisu5** [comment]
Here you go!

**For current Aegis** (recommended for now):
https://github.com/aegis-icons/aegis-icons/blob/master/PNG/Hurricane%20Electric%20Internet%20Service.png

**For [Aegis beta version](https://github.com/beemdevelopment/Aegis/releases/tag/v2.0-beta1):**
https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Hurricane%20Electric%20Internet%20Service.svg
