### ISSUE TITLE
Icon request: 1984 Hosting

### ISSUE THREAD

**Issue by IzumiSenaSora** [aegis-icons/aegis-icons#231]
- URL of the site or app **(required):** https://www.1984hosting.com/
- Logo resources for the icon **(optional, but recommended):** https://www.1984hosting.com/static/img/1984-logo.png

**Comment by krisu5** [comment]
No high quality images or vectors of this logo. I'm trying get somebody to identify the font so I can recreate the logo.

I'm also emailing 1984 Hosting to possibly get at least higher quality image of the logo.

If either of the things fails, unfortunately I have to drop this one then.

For now, this is on hold.

**Comment by krisu5** [comment]
Font was found (it was Nitti Medium) and logo was recreated.

**For current Aegis** (recommended for now):
https://github.com/aegis-icons/aegis-icons/blob/master/PNG/1984%20Hosting.png
https://github.com/aegis-icons/aegis-icons/blob/master/PNG/Variations/1984%20Hosting%20bg.var.png

**For [Aegis beta version](https://github.com/beemdevelopment/Aegis/releases/tag/v2.0-beta1):**
https://github.com/aegis-icons/aegis-icons/blob/master/SVG/1984%20Hosting.svg
https://github.com/aegis-icons/aegis-icons/blob/master/SVG/.Variations/1984%20Hosting%20bg.var.svg
