### ISSUE TITLE
Icon request: Namebase

### ISSUE THREAD

**Issue by IzumiSenaSora** [aegis-icons/aegis-icons#232]
- URL of the site or app **(required):** https://www.namebase.io/
- Logo resources for the icon **(optional, but recommended):** https://avatars.githubusercontent.com/u/41350437?s=200&v=4

**Comment by krisu5** [comment]
Here you go!

**For current Aegis** (recommended for now):
https://github.com/aegis-icons/aegis-icons/blob/master/PNG/Namebase.png

**For [Aegis beta version](https://github.com/beemdevelopment/Aegis/releases/tag/v2.0-beta1):**
https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Namebase.svg
