### ISSUE TITLE
Icon request: CoinEx

### ISSUE THREAD

**Issue by IzumiSenaSora** [aegis-icons/aegis-icons#233]
- URL of the site or app **(required):** https://www.coinex.com/
- Logo resources for the icon **(optional, but recommended):** https://www.coinex.com/assets/img/logo-white.png

**Comment by krisu5** [comment]
Here you go!

**For current Aegis** (recommended for now):
https://github.com/aegis-icons/aegis-icons/blob/master/PNG/CoinEx.png

**For [Aegis beta version](https://github.com/beemdevelopment/Aegis/releases/tag/v2.0-beta1):**
https://github.com/aegis-icons/aegis-icons/blob/master/SVG/CoinEx.svg
