### ISSUE TITLE
Icon request: Epik

### ISSUE THREAD

**Issue by IzumiSenaSora** [aegis-icons/aegis-icons#234]
- URL of the site or app **(required):** https://www.epik.com/
- Logo resources for the icon **(optional, but recommended):** https://www.epik.com/home-v3/img/svg/logo.svg

**Comment by krisu5** [comment]
For ethical reasons, I won't do this one. Epik is known for hosting most notorious far-right sites, partically breaks [guideline #5](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines).

"Internet globe" icon is alternative option.
