### ISSUE TITLE
Icon request: minerstat

### ISSUE THREAD

**Issue by srekoslav** [aegis-icons/aegis-icons#235]
- URL of the site or app **(required):** https://www.minerstat.com
- Logo resources for the icon **(optional, but recommended):** https://minerstat.com/downloads/minerstat-logo-light-svg.zip

**Comment by krisu5** [comment]
Here you go!

**For current Aegis** (recommended for now):
https://github.com/aegis-icons/aegis-icons/blob/master/PNG/minerstat.png

**For [Aegis beta version](https://github.com/beemdevelopment/Aegis/releases/tag/v2.0-beta1):**
https://github.com/aegis-icons/aegis-icons/blob/master/SVG/minerstat.svg
