### ISSUE TITLE
Icon request: Mapbox

### ISSUE THREAD

**Issue by IzumiSenaSora** [aegis-icons/aegis-icons#236]
- URL of the site or app **(required):** https://www.mapbox.com/
- Logo resources for the icon **(optional, but recommended):** https://assets.website-files.com/5def5247146d40b977b337a3/5def5247146d40a8e2b337fb_logo-transparent.svg

**Comment by krisu5** [comment]
Here you go!

**For current Aegis** (recommended for now):
https://github.com/aegis-icons/aegis-icons/blob/master/PNG/Mapbox.png
https://github.com/aegis-icons/aegis-icons/blob/master/PNG/Variations/Mapbox%20bg.var.png

**For [Aegis beta version](https://github.com/beemdevelopment/Aegis/releases/tag/v2.0-beta1):**
https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Mapbox.svg
https://github.com/aegis-icons/aegis-icons/blob/master/SVG/.Variations/Mapbox%20bg.var.svg
