### ISSUE TITLE
Icon request: Exact

### ISSUE THREAD

**Issue by alexbakker** [aegis-icons/aegis-icons#237]
- URL of the site or app **(required):** https://www.exact.com
- Logo resources for the icon **(optional, but recommended):** https://files.exact.com/static/rainbow/v0/img/exact-logo.svg

**Comment by krisu5** [comment]
Here you go!

**For current Aegis** (recommended for now):
https://github.com/aegis-icons/aegis-icons/blob/master/PNG/Exact.png

**For [Aegis beta version](https://github.com/beemdevelopment/Aegis/releases/tag/v2.0-beta1):**
https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Exact.svg
