### ISSUE TITLE
Update icon: Discord

### ISSUE THREAD

**Issue by u8Jj3** [aegis-icons/aegis-icons#241]
- URL of the site or app **(required):** https://discord.com
- Reason for update **(required):** New branding
- Logo resources for the icon **(optional, but recommended):** https://discord.com/brand-new/branding

**Comment by krisu5** [comment]
Updated!

**For current Aegis** (recommended for now):
https://github.com/aegis-icons/aegis-icons/blob/master/PNG/Discord%20v2.png

**For [Aegis beta version](https://github.com/beemdevelopment/Aegis/releases/tag/v2.0-beta2):**
https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Discord%20v2.svg
