### ISSUE TITLE
Icon request: Hover

### ISSUE THREAD

**Issue by billwieboldt** [aegis-icons/aegis-icons#242]
- URL of the site or app: https://www.hover.com
- Logo resources for the icon: https://commons.wikimedia.org/wiki/File:Hover_logo.svg

**Comment by krisu5** [comment]
Here you go!

**For current Aegis** (recommended for now):
https://github.com/aegis-icons/aegis-icons/blob/master/PNG/Hover.png

**For [Aegis beta version](https://github.com/beemdevelopment/Aegis/releases/tag/v2.0-beta2):**
https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Hover.svg
