### ISSUE TITLE
Icon request: FreeTaxUSA Free Tax Filing

### ISSUE THREAD

**Issue by kashifkhan** [aegis-icons/aegis-icons#243]
- URL of the site or app : https://www.freetaxusa.com/

**Comment by krisu5** [comment]
SVG: https://commons.wikimedia.org/wiki/File:Global_Entry_Logo_Negative.svg

**Comment by kashifkhan** [comment]
> SVG: https://commons.wikimedia.org/wiki/File:Global_Entry_Logo_Negative.svg

I think this one is for the Global Entry issue I created not for FreeTaxUSA ?

**Comment by krisu5** [comment]
> I think this one is for the Global Entry issue I created not for FreeTaxUSA ?

Yeah, wrong issue.

**Comment by krisu5** [comment]
Here you go!

**For latest Aegis** (recommended):
https://github.com/aegis-icons/aegis-icons/blob/master/SVG/FreeTaxUSA.svg

**For older version of Aegis**:
https://github.com/aegis-icons/aegis-icons/blob/master/PNG/FreeTaxUSA.png
