### ISSUE TITLE
Icon request: Wyze

### ISSUE THREAD

**Issue by kashifkhan** [aegis-icons/aegis-icons#244]
- URL of the site or app: https://wyze.com/

**Comment by krisu5** [comment]
Here you go!

**For latest Aegis** (recommended):
https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Wyze.svg

**For older version of Aegis**:
https://github.com/aegis-icons/aegis-icons/blob/master/PNG/Wyze.png
