### ISSUE TITLE
Icon request: Global Entry

### ISSUE THREAD

**Issue by kashifkhan** [aegis-icons/aegis-icons#245]
URL of the site or app: https://www.cbp.gov/travel/trusted-traveler-programs/global-entry

**Comment by krisu5** [comment]
SVG: https://commons.wikimedia.org/wiki/File:Global_Entry_Logo_Negative.svg

**Comment by krisu5** [comment]
Here you go!

**For latest Aegis** (recommended):
https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Global%20Entry.svg

**For older version of Aegis**:
https://github.com/aegis-icons/aegis-icons/blob/master/PNG/Global%20Entry.png
