### ISSUE TITLE
Icon request: ClickUp

### ISSUE THREAD

**Issue by skozharinov** [aegis-icons/aegis-icons#246]
- URL of the site or app **(required):** https://clickup.com/
- Logo resources for the icon **(optional, but recommended):** https://clickup.com/images/brand-assets/logotype/symbol-white.zip

**Comment by krisu5** [comment]
Here you go!

**For latest Aegis** (recommended):
https://github.com/aegis-icons/aegis-icons/blob/master/SVG/ClickUp.svg

**For older version of Aegis**:
https://github.com/aegis-icons/aegis-icons/blob/master/PNG/ClickUp.png
