### ISSUE TITLE
Icon submission: OnlyFans

### ISSUE THREAD

**Issue by skozharinov** [aegis-icons/aegis-icons#248]
- [x] I have read and followed CONTRIBUTING document.
- URL of the site or app **(required, unless it's generic icon):** https://onlyfans.com/  (NSFW)
- Where did you took the BG color(s) **(required, unless it's generic icon):** https://onlyfans.com/theme/onlyfans/spa/brand/OnlyFans_Social_Icons.zip

Uploaded files:
[OnlyFans.zip](https://github.com/aegis-icons/aegis-icons/files/6565246/OnlyFans.zip)

**Comment by krisu5** [comment]
Well, that's weird. They still use old branding on the main site even when they have published this one.

I let this pass, because it most likely will be updated to this near future.

Anyways, logo was too big, so I had to change that.

**Comment by krisu5** [comment]
I have been following if OF does rebrand with this logo, but seems like their brand page is back with old logo: https://onlyfans.com/brand (my guess: new one looks too much like Twitter's logo)

And homepage is still using old logo also.

Unsure if this rebrand happens or not, I will change it to "old" logo for now (or current logo, how knows anymore). Your name will stay on credits.

If change happens, obviously I will update it back to that new logo.

Others who are reading this and wondering what was this new logo, here it is:

![Artboard 1](https://user-images.githubusercontent.com/3540275/120473723-00cc9500-c3b0-11eb-91cc-7d5627687b71.png)

![OnlyFans_Social_Icon_Circle_Blue](https://user-images.githubusercontent.com/3540275/120473227-78e68b00-c3af-11eb-8a49-ea212faeb256.png)
