### ISSUE TITLE
Icon submission: Qwintry

### ISSUE THREAD

**Issue by skozharinov** [aegis-icons/aegis-icons#249]
- [x] I have read and followed CONTRIBUTING document.
- URL of the site or app **(required, unless it's generic icon):** https://qwintry.com/
- Where did you took the BG color(s) **(required, unless it's generic icon):** https://qwintry.com/images/static/logo-en.svg

Uploaded files:
[Qwintry.zip](https://github.com/aegis-icons/aegis-icons/files/6565252/Qwintry.zip)

**Comment by krisu5** [comment]
Thanks for contribution, but logo wasn't centered. Had to update that.
