### ISSUE TITLE
Icon submission: Upwork

### ISSUE THREAD

**Issue by skozharinov** [aegis-icons/aegis-icons#250]
- [x] I have read and followed CONTRIBUTING document.
- URL of the site or app **(required, unless it's generic icon):** https://www.upwork.com/
- Where did you took the BG color(s) **(required, unless it's generic icon):** https://vault.pactsafe.io/s/6624a68d-7fb5-4b00-aeb3-786655460f3c/assets/SkXpW6OTG.svg

Uploaded files:
[Upwork.zip](https://github.com/aegis-icons/aegis-icons/files/6565254/Upwork.zip)

**Comment by krisu5** [comment]
Thanks for submission, but branding was outdated on this one. I updated it to current branding.
