### ISSUE TITLE
Icon request: Xero

### ISSUE THREAD

**Issue by 00dani** [aegis-icons/aegis-icons#251]
- URL of the site or app: https://xero.com/
- Logo resources for the icon: https://en.wikipedia.org/wiki/File:Xero_software_logo.svg

Xero is a popular SaaS platform for managing payroll and other accounting needs - it's common for each employee to have their own login to access their payslips, and it supports TOTP for securing your account, so it's likely lots of people will be using 2FA with this service. I personally am using Aegis for authentication into Xero right now, and I was surprised it wasn't already included in aegis-icons.

Helpfully, their current logo seems to be available as an SVG from Wikimedia, which should make it straightforward to add the logo to the collection.

**Comment by krisu5** [comment]
Here you go!

**For Aegis v2.0 and above** (recommended):
https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Xero.svg

**For Aegis v1.4.2 and below**:
https://github.com/aegis-icons/aegis-icons/blob/master/PNG/Xero.png

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

**Comment by 00dani** [comment]
Oops, I installed this earlier in the week and forgot to say thank you! Thank you! It's looking great. 👍
