### ISSUE TITLE
Icon request: TransIP (www.transip.nl)

### ISSUE THREAD

**Issue by Xaero** [aegis-icons/aegis-icons#252]
- URL of the site or app **(required):** TransIP (www.transip.nl)
- Logo resources for the icon **(optional, but recommended):**
https://svgshare.com/i/Xhh.svg
https://www.transip.nl/img/transip-new/favicons/apple-touch-icon.png

**Comment by krisu5** [comment]
Here you go!

**For Aegis v2.0 and above** (recommended):
https://github.com/aegis-icons/aegis-icons/blob/master/SVG/TransIP.svg

**For Aegis v1.4.2 and below**:
https://github.com/aegis-icons/aegis-icons/blob/master/PNG/TransIP.png

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*
