### ISSUE TITLE
Icon request: SendGrid (www.sendgrid.com)

### ISSUE THREAD

**Issue by Xaero** [aegis-icons/aegis-icons#253]
- URL of the site or app **(required):** SendGrid (www.sendgrid.com)
- Logo resources for the icon **(optional, but recommended):** 
https://sendgrid.com/resource/brand/

**Comment by krisu5** [comment]
Here you go!

**For Aegis v2.0 and above** (recommended):
https://github.com/aegis-icons/aegis-icons/blob/master/SVG/SendGrid.svg

**For Aegis v1.4.2 and below**:
https://github.com/aegis-icons/aegis-icons/blob/master/PNG/SendGrid.png

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*
