### ISSUE TITLE
Icon request: DirectAdmin

### ISSUE THREAD

**Issue by rubenelshof** [aegis-icons/aegis-icons#254]
- URL of the site or app **(required):** DirectAdmin (https://directadmin.com)
- Logo resources for the icon
https://www.directadmin.com/extras-logos.php

**Comment by krisu5** [comment]
Here you go!

**For Aegis v2.0 and above** (recommended):
https://github.com/aegis-icons/aegis-icons/blob/master/SVG/DirectAdmin.svg

**For Aegis v1.4.2 and below**:
https://github.com/aegis-icons/aegis-icons/blob/master/PNG/DirectAdmin.png

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*
