### ISSUE TITLE
Icon submission: 1040.com

### ISSUE THREAD

**Issue by justsomemate** [aegis-icons/aegis-icons#255]
- [x] I have read and followed CONTRIBUTING document.
- URL of the site or app **(required, unless it's generic icon):** https://www.1040.com
- Where did you take the BG color(s) **(required, unless it's generic icon):** Logo color
- Logo resources for the icon:
  - https://1040.staticserve.net/assets/images/2019/logo-mark-1040-2.svg

Uploaded files:
[1040.com.zip](https://github.com/aegis-icons/aegis-icons/files/6570526/1040.com.zip)

**Comment by krisu5** [comment]
Added to the repo! 👍
