### ISSUE TITLE
Icon pack import issue

### ISSUE THREAD

**Issue by Kelvino9** [aegis-icons/aegis-icons#256]
Icon pack cannot be imported to Aegis 2.0 if the name of the zip file has upper case letters.

More of an Aegis issue, but I thought you should be aware of this issue while it exists.

Issue has been reported [here](https://github.com/beemdevelopment/Aegis/issues/757).

**Comment by krisu5** [comment]
I didn't personally have this issue, tested with downloaded ZIP and worked fine without any renaming.
