### ISSUE TITLE
Icon request: myanimelist.net

### ISSUE THREAD

**Issue by pokegamer5547** [aegis-icons/aegis-icons#257]
https://myanimelist.net/

**Comment by krisu5** [comment]
Here you go!

**For Aegis v2.0 and above** (recommended):
https://github.com/aegis-icons/aegis-icons/blob/master/SVG/MyAnimeList.svg

**For Aegis v1.4.2 and below**:
https://github.com/aegis-icons/aegis-icons/blob/master/PNG/MyAnimeList.png

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

**Comment by pokegamer5547** [comment]
Ah but i couldn't find this icon in my aegis 2.0 app. I have imported latest icon pack release too and searched it exactly but couldn't find it.

**Comment by krisu5** [comment]
It's not in the pack, pack updates happen monthly.

Download icon from link in my comment & then click and read "How to add icon(s) to Aegis?" link.

**Comment by pokegamer5547** [comment]
Ah i see, i get it now. thankyou so much! :) i will for pack to add it instead next month.
