### ISSUE TITLE
Icon submission: Critical Start

### ISSUE THREAD

**Issue by justsomemate** [aegis-icons/aegis-icons#259]
- [x] I have read and followed CONTRIBUTING document.
- URL of the site or app **(required, unless it's generic icon):** https://www.criticalstart.com
- Where did you took the BG color(s) **(required, unless it's generic icon):** Official logo uses the colors #009BDE and #004A97. I couldn't find a brand page, but the website emphasizes the lighter color, so I used it.
- Logo resources for the icon:
  - Logos linked on the website are SVGs with embedded PNGs (https://www.criticalstart.com/wp-content/uploads/2020/12/CS-Logo_Horizontal-color.svg), and I couldn't find a brand page.
  - I requested real SVGs from them and used one of the files they emailed me to build the icon.

Uploaded files:
[CriticalStart.zip](https://github.com/aegis-icons/aegis-icons/files/6586516/CriticalStart.zip)

**Comment by krisu5** [comment]
Thanks for your submission again! Slight nitpicking, but made logo tiny bit bigger and center it based of the ring, so it looks more visually center. https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Critical%20Start.svg
