### ISSUE TITLE
Icon request: privacy.com, autistici.org, nitrogensports.eu, electrum.org

### ISSUE THREAD

**Issue by fjordmoco** [aegis-icons/aegis-icons#26]
URLs of the site or app (required):

https://privacy.com
https://autistici.org
https://nitrogensports.eu
https://electrum.org

**Comment by krisu5** [comment]
Note: there's already [generic bitcoin icon](https://github.com/krisu5/aegis-icons/blob/master/PNG/Generic%20Icons/Bitcoin.png).

Because of that, icon for Electrum Bitcoin Wallet seems kinda redundant.

**Comment by krisu5** [comment]
Done.

Autistici: https://github.com/krisu5/aegis-icons/blob/master/PNG/Autistici.png
Nitrogen Sports: https://github.com/krisu5/aegis-icons/blob/master/PNG/Nitrogen%20Sports.png
Privacy: https://github.com/krisu5/aegis-icons/blob/master/PNG/Privacy.png
Electrum: ignored, use generic [bitcoin icon](https://github.com/krisu5/aegis-icons/blob/master/PNG/Generic%20Icons/Bitcoin.png)
