### ISSUE TITLE
Icon request: Infomaniak

### ISSUE THREAD

**Issue by gregorydk** [aegis-icons/aegis-icons#260]
- URL of the site or app **(required):** https://www.infomaniak.com/
- Logo resources for the icon **(optional, but recommended):** https://www.infomaniak.com/img/common/logo-infomaniak-small.svg

![apple-touch-icon-144x144](https://user-images.githubusercontent.com/7804464/120622608-41cfb280-c45f-11eb-813c-62d698b5e403.png)

**Comment by krisu5** [comment]
Here you go!

**For Aegis v2.0 and above** (recommended):
https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Infomaniak.svg

**For Aegis v1.4.2 and below**:
https://github.com/aegis-icons/aegis-icons/blob/master/PNG/Infomaniak.png

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*
