### ISSUE TITLE
Icon request: Pixelfed

### ISSUE THREAD

**Issue by gregorydk** [aegis-icons/aegis-icons#261]
- URL of the site or app **(required):** https://pixelfed.social/
- Logo resources for the icon **(optional, but recommended):** https://pixelfed.social/img/pixelfed-icon-color.svg

![favicon](https://user-images.githubusercontent.com/7804464/120624802-5614af00-c461-11eb-92c9-e61efd216b8e.png)

**Comment by krisu5** [comment]
Here you go!

**For Aegis v2.0 and above** (recommended):
https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Pixelfed.svg

**For Aegis v1.4.2 and below**:
https://github.com/aegis-icons/aegis-icons/blob/master/PNG/Pixelfed.png

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*
