### ISSUE TITLE
Icon request: Box

### ISSUE THREAD

**Issue by syntheticbit** [aegis-icons/aegis-icons#262]
- URL of the site or app **(required):** https://www.box.com/
- Logo resources for the icon **(optional, but recommended):** https://cloud.app.box.com/s/orjwhx28cvqr2dfhxyf2et253okqkoxm

**Comment by krisu5** [comment]
Here you go!

**For Aegis v2.0 and above** (recommended):
https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Box.svg

**For Aegis v1.4.2 and below**:
https://github.com/aegis-icons/aegis-icons/blob/master/PNG/Box.png

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*
