### ISSUE TITLE
Icon request: Guilded

### ISSUE THREAD

**Issue by syntheticbit** [aegis-icons/aegis-icons#263]
- URL of the site or app **(required):** https://www.guilded.gg/
- Logo resources for the icon **(optional, but recommended):** https://img.guildedcdn.com/asset/Logos/logomark/Color/Guilded_Logomark_Color.svg?ver=3

**Comment by krisu5** [comment]
Here you go!

**For Aegis v2.0 and above** (recommended):
https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Guilded.svg

**For Aegis v1.4.2 and below**:
https://github.com/aegis-icons/aegis-icons/blob/master/PNG/Guilded.png

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*
