### ISSUE TITLE
Icon request: Qantas

### ISSUE THREAD

**Issue by wagensveld** [aegis-icons/aegis-icons#264]
- URL of the site or app **(required):** https://www.qantas.com/au/en.html
- Logo resources for the icon **(optional, but recommended):** https://logodownload.org/wp-content/uploads/2020/03/qantas-airways-logo-6.png

**Comment by krisu5** [comment]
Here you go!

**For Aegis v2.0 and above** (recommended):
https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Qantas.svg

**For Aegis v1.4.2 and below**:
https://github.com/aegis-icons/aegis-icons/blob/master/PNG/Qantas.png

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*
