### ISSUE TITLE
Icon request: Populi

### ISSUE THREAD

**Issue by bannurowi** [aegis-icons/aegis-icons#265]
- URL of the site or app **(required):** https://populi.co/
- Logo resources for the icon **(optional, but recommended):** https://populi.co/safari-pinned-tab.svg?v=oLJb48QEl3
   + Logo color is #2fabe1 on the website

**Comment by krisu5** [comment]
Here you go!

**For Aegis v2.0 and above** (recommended):
https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Populi.svg

**For Aegis v1.4.2 and below**:
https://github.com/aegis-icons/aegis-icons/blob/master/PNG/Populi.png

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*
