### ISSUE TITLE
Icon request: Groups.io

### ISSUE THREAD

**Issue by bannurowi** [aegis-icons/aegis-icons#266]
- URL of the site or app **(required):** https://groups.io/

**Comment by krisu5** [comment]
Here you go!

**For Aegis v2.0 and above** (recommended):
https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Groups.io.svg

**For Aegis v1.4.2 and below**:
https://github.com/aegis-icons/aegis-icons/blob/master/PNG/Groups.io.png

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*
