### ISSUE TITLE
Icon request: Glimesh

### ISSUE THREAD

**Issue by syntheticbit** [aegis-icons/aegis-icons#268]
- URL of the site or app **(required):** https://glimesh.tv/
- Logo resources for the icon **(optional, but recommended):** https://github.com/Glimesh/assets/blob/master/logos/Logo%20no%20Text.png

**Comment by krisu5** [comment]
Here you go!

**For Aegis v2.0 and above** (recommended):
https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Glimesh.svg

**For Aegis v1.4.2 and below**:
https://github.com/aegis-icons/aegis-icons/blob/master/PNG/Glimesh.png

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*
