### ISSUE TITLE
Icon request: Magento

### ISSUE THREAD

**Issue by rubenelshof** [aegis-icons/aegis-icons#269]
- URL of the site or app **(required):** Magento (https://magento.com)
- Logo resources for the icon **(optional, but recommended):** 
https://en.wikipedia.org/wiki/File:Magento.svg

**Comment by krisu5** [comment]
Current logo from Wikipedia (just in case): https://commons.wikimedia.org/wiki/File:Magento_Logo.svg

**Comment by krisu5** [comment]
Here you go!

**For Aegis v2.0 and above** (recommended):
https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Magento.svg

**For Aegis v1.4.2 and below**:
https://github.com/aegis-icons/aegis-icons/blob/master/PNG/Magento.png

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*
