### ISSUE TITLE
Icon variations

### ISSUE THREAD

**Issue by krisu5** [aegis-icons/aegis-icons#27]
For icons that has...

- ...dark background, that blends into the dark / amoled theme (eg. Steam, Ubisoft, Uber etc. etc.) #24 
   - Make either bordered versions or different color variations
- ...bad contrast with white foreground (eg. Snapchat, Mailchimp)
   - Make variations that has black icons

**Comment by Wilker-uwu** [comment]
maybe something could be done either in Aegis or here to manipulate the SVGs by itself with themes in the program. what do you think? would opening an issue in Aegis be good? :3

**Comment by krisu5** [comment]
Maybe, [better icon support is work in progress](https://github.com/beemdevelopment/Aegis/pull/221#issuecomment-541868541) and it's unsure yet if they gonna use my icons or not. Either way is fine.

The main goal of this project wasn't that anyways, my goal was just make icons for users that can use them right now. From the start, I knew that this was temporary solution.

It's unsure if I continue or retransform this project after new icon system is implemented, depends on how the new icon system works.
