### ISSUE TITLE
Icon submission: Packagist

### ISSUE THREAD

**Issue by gr99t** [aegis-icons/aegis-icons#270]
- [x] I have read and followed CONTRIBUTING document.
- URL of the site or app **(required, unless it's generic icon):** https://packagist.org/
- Where did you took the BG color(s) **(required, unless it's generic icon):** Website banner
- Icon source: https://github.com/simple-icons/simple-icons/blob/master/icons/packagist.svg

Uploaded files:
[packagist.zip](https://github.com/aegis-icons/aegis-icons/files/6602513/packagist.zip)

**Comment by krisu5** [comment]
Added to repo!
