### ISSUE TITLE
Icon submission: Ionos

### ISSUE THREAD

**Issue by devmrcl** [aegis-icons/aegis-icons#271]
- [x] I have read and followed CONTRIBUTING document.
- URL of the site or app **(required, unless it's generic icon):** https://www.ionos.de/
- Icon source: https://ce1.uicdn.net/7d5/abcb6399cfff8a905569278386360/frontend-skin-thunder/vi-logo.svg

Uploaded files:
[ionos.zip](https://github.com/aegis-icons/aegis-icons/files/6602589/ionos.zip)

**Comment by krisu5** [comment]
Logo was too wide, so I resized that: https://github.com/aegis-icons/aegis-icons/blob/master/SVG/IONOS.svg
