### ISSUE TITLE
Icon submission: Bitrix24

### ISSUE THREAD

**Issue by devmrcl** [aegis-icons/aegis-icons#272]
- [x] I have read and followed CONTRIBUTING document.
- URL of the site or app **(required, unless it's generic icon):** https://www.bitrix24.com/
- Where did you took the BG color(s) **(required, unless it's generic icon):** Bitrix24 Basic brand book (https://bitrixsoft.com/download/files/partners-en/Bitrix_media_kit.zip)

Uploaded files:
[bitrix24.zip](https://github.com/aegis-icons/aegis-icons/files/6602594/bitrix24.zip)

**Comment by krisu5** [comment]
Added to the repo with minor changes: https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Bitrix24.svg
