### ISSUE TITLE
Icon request: Active24, Gaijin Entertainment, WEDOS

### ISSUE THREAD

**Issue by ghost** [aegis-icons/aegis-icons#273]
Hello
I have never posted a query here so please don't be angry if I put my query in the wrong topic.
I downloaded your icons today and I'm really excited :-)
But I noticed that for a couple of popular services that use 2FA authentication the icons are missing.
Below I have listed the sites for which the icons are not yet available

https://www.wedos.com/
https://www.active24.co.uk/
https://gaijin.net/

So could you please consider creating icons for these services ?
Thank you very much :-)

**Comment by krisu5** [comment]
It's okay, next time just add names of the apps / sites to the issue title.

### Active24

**For Aegis v2.0 and above** (recommended):
https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Active24.svg

**For Aegis v1.4.2 and below**:
https://github.com/aegis-icons/aegis-icons/blob/master/PNG/Active24.png

### Gaijin Entertaiment

**For Aegis v2.0 and above** (recommended):
https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Gaijin%20Entertainment.svg
https://github.com/aegis-icons/aegis-icons/blob/master/SVG/.Variations/Gaijin%20Entertainment%20bg.var.svg

**For Aegis v1.4.2 and below**:
https://github.com/aegis-icons/aegis-icons/blob/master/PNG/Gaijin%20Entertainment.png
https://github.com/aegis-icons/aegis-icons/blob/master/PNG/Variations/Gaijin%20Entertainment%20bg.var.png

### WEDOS

**For Aegis v2.0 and above** (recommended):
https://github.com/aegis-icons/aegis-icons/blob/master/SVG/WEDOS.svg

**For Aegis v1.4.2 and below**:
https://github.com/aegis-icons/aegis-icons/blob/master/PNG/WEDOS.png

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

**Comment by ghost** [comment]
Hello
Thank you very much for the quick response and adding the requested icons.
You are great :-)
