### ISSUE TITLE
Icon request: Pcloud

### ISSUE THREAD

**Issue by theLittlePrinceAD** [aegis-icons/aegis-icons#274]
Icon request for "Pcloud"
https://my.pcloud.com/
Thank you.

- URL of the site or app **(required):** 
- Logo resources for the icon **(optional, but recommended):**

**Comment by krisu5** [comment]
Already exists: https://github.com/aegis-icons/aegis-icons/blob/master/SVG/pCloud.svg

**Comment by theLittlePrinceAD** [comment]
My fault! Excuse me :( Have a good luck!

**Comment by krisu5** [comment]
No problem 😅
