### ISSUE TITLE
Icon request: Webmin

### ISSUE THREAD

**Issue by m-rm** [aegis-icons/aegis-icons#276]
- URL of the site or app **(required):** https://www.webmin.com/
- Logo resources for the icon **(optional, but recommended):** 

I can't find a good official resource for the logo. There is an unofficial SVG version: https://iconify.design/icon-sets/logos/webmin.html but I would prefer the logo without perspective such as this one: https://images.app.goo.gl/pxXj1cajT9s2L5MA6

**Comment by krisu5** [comment]
Official presentation of the logo is with perspective, so I stick to it (specially when logo in [Simple Icons](https://simpleicons.org/?q=webmin) has it exactly like that too).

**For Aegis v2.0 and above** (recommended):
https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Webmin.svg

**For Aegis v1.4.2 and below**:
https://github.com/aegis-icons/aegis-icons/blob/master/PNG/Webmin.png

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

**Comment by m-rm** [comment]
Thank you very much!
