### ISSUE TITLE
Icon request: Tweakers.net

### ISSUE THREAD

**Issue by CyberJack** [aegis-icons/aegis-icons#277]
- URL of the site or app **(required):** https://tweakers.net
- Logo resources for the icon **(optional, but recommended):** https://tweakers.net/info/over-tweakers/logo-tweakers/  
  The link to "Het logo voor digitaal gebruik." contains a zip with the logo in pdf, png, and ai format.

Tweakers added support for 2FA since April 28, 2021.

**Comment by krisu5** [comment]
Here you go!

**For Aegis v2.0 and above** (recommended):
https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Tweakers.svg
https://github.com/aegis-icons/aegis-icons/blob/master/SVG/.Variations/Tweakers%20fg.var.svg

**For Aegis v1.4.2 and below**:
https://github.com/aegis-icons/aegis-icons/blob/master/PNG/Tweakers.png
https://github.com/aegis-icons/aegis-icons/blob/master/PNG/Variations/Tweakers%20fg.var.png

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*
