### ISSUE TITLE
Icon request: Truenas

### ISSUE THREAD

**Issue by m-rm** [aegis-icons/aegis-icons#278]
- URL of the site or app **(required):** https://www.truenas.com/
- Logo resources for the icon **(optional, but recommended):** 

Can't find a good logo resource. There is an official logo page https://www.ixsystems.com/logos-truenas-ixsystems/ where they updated to the new logos, but the link to the high resolution version leads to the old, outdated logos.

**Comment by krisu5** [comment]
Fortunately the logo on the header is SVG 🙂

**For Aegis v2.0 and above** (recommended):
https://github.com/aegis-icons/aegis-icons/blob/master/SVG/TrueNAS.svg

**For Aegis v1.4.2 and below**:
https://github.com/aegis-icons/aegis-icons/blob/master/PNG/TrueNAS.png

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

**Comment by m-rm** [comment]
Thanks!
