### ISSUE TITLE
Icon request for WazirX and CoinDCX

### ISSUE THREAD

**Issue by Observing9616** [aegis-icons/aegis-icons#279]
I'd like to request icons for the cryptocurrency exchanges WazirX and CoinDCX.

Their URLs are as follows:
WazirX.com
CoinDCX.com

**Comment by krisu5** [comment]
Here you go!

**For Aegis v2.0 and above** (recommended):
https://github.com/aegis-icons/aegis-icons/blob/master/SVG/WazirX.svg
https://github.com/aegis-icons/aegis-icons/blob/master/SVG/CoinDCX.svg

**For Aegis v1.4.2 and below**:
https://github.com/aegis-icons/aegis-icons/blob/master/PNG/WazirX.png
https://github.com/aegis-icons/aegis-icons/blob/master/PNG/CoinDCX.png

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*
