### ISSUE TITLE
Icon request: Discogs

### ISSUE THREAD

**Issue by jhenninger** [aegis-icons/aegis-icons#280]
- URL of the site or app **(required):** https://www.discogs.com
- Logo resources for the icon **(optional, but recommended):** https://www.discogs.com/brand

P.S. Thanks a lot for this project :)

**Comment by krisu5** [comment]
> P.S. Thanks a lot for this project :)

No problem!

**For Aegis v2.0 and above** (recommended):
https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Discogs.svg
https://github.com/aegis-icons/aegis-icons/blob/master/SVG/.Variations/Discogs%20bg.var.svg
https://github.com/aegis-icons/aegis-icons/blob/master/SVG/.Variations/Discogs%20fg.bg.var.svg

**For Aegis v1.4.2 and below**:
https://github.com/aegis-icons/aegis-icons/blob/master/PNG/Discogs.png
https://github.com/aegis-icons/aegis-icons/blob/master/PNG/Variations/Discogs%20bg.var.png
https://github.com/aegis-icons/aegis-icons/blob/master/PNG/Variations/Discogs%20fg.bg.var.png

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*
