### ISSUE TITLE
Icon request: Adafruit

### ISSUE THREAD

**Issue by Otiel** [aegis-icons/aegis-icons#281]
- URL of the site or app: https://www.adafruit.com
- Logo resources for the icon: [adafruit_favicon.zip](https://github.com/aegis-icons/aegis-icons/files/6715920/adafruit_favicon.zip)
Preview:
![image](https://user-images.githubusercontent.com/3851902/123421360-05eebf80-d5bd-11eb-9dc4-6080b83823ca.png)

**Comment by krisu5** [comment]
Here you go!

**For Aegis v2.0 and above** (recommended):
https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Adafruit.svg
https://github.com/aegis-icons/aegis-icons/blob/master/SVG/.Variations/Adafruit%20bg.var.svg

**For Aegis v1.4.2 and below**:
https://github.com/aegis-icons/aegis-icons/blob/master/PNG/Adafruit.png
https://github.com/aegis-icons/aegis-icons/blob/master/PNG/Variations/Adafruit%20bg.var.png

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

**Comment by Otiel** [comment]
Perfect, thanks for you work!
