### ISSUE TITLE
Icon request: SOGo

### ISSUE THREAD

**Issue by Otiel** [aegis-icons/aegis-icons#282]
- URL of the site or app: https://www.sogo.nu
- Logo resources for the icon: 
  - https://www.sogo.nu/img/sogo.svg
  - https://www.sogo.nu/favicon.ico

**Comment by krisu5** [comment]
Here you go!

**For Aegis v2.0 and above** (recommended):
https://github.com/aegis-icons/aegis-icons/blob/master/SVG/SOGo.svg

**For Aegis v1.4.2 and below**:
https://github.com/aegis-icons/aegis-icons/blob/master/PNG/SOGo.png

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

**Comment by Otiel** [comment]
Thank you!
