### ISSUE TITLE
Icon request: Icedrive

### ISSUE THREAD

**Issue by m0yP** [aegis-icons/aegis-icons#284]
- URL of the site or app **(required):** https://icedrive.net
- Logo resources for the icon **(optional, but recommended):**

**Comment by krisu5** [comment]
Here you go!

**For Aegis v2.0 and above** (recommended):
https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Icedrive.svg

**For Aegis v1.4.2 and below**:
https://github.com/aegis-icons/aegis-icons/blob/master/PNG/Icedrive.png

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

**Comment by m0yP** [comment]
Thank you!
