### ISSUE TITLE
Icon request: Hubspot

### ISSUE THREAD

**Issue by sdotb** [aegis-icons/aegis-icons#285]
- URL of the site or app: https://www.hubspot.com/ 
- Logo resources for the icon **(optional, but recommended):** [https://worldvectorlogo.com/download/hubspot-1.svg](url)

**Comment by krisu5** [comment]
Here you go!

**For Aegis v2.0 and above** (recommended):
https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Hubspot.svg

**For Aegis v1.4.2 and below**:
https://github.com/aegis-icons/aegis-icons/blob/master/PNG/Hubspot.png

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*
