### ISSUE TITLE
Icon request: AllMyLinks

### ISSUE THREAD

**Issue by AliNemati13** [aegis-icons/aegis-icons#286]
- URL of the site or app **(required):** https://allmylinks.com/
- Logo resources for the icon **(optional, but recommended):** https://logos.fandom.com/wiki/AllMyLinks

**Comment by krisu5** [comment]
Here you go!

**For Aegis v2.0 and above** (recommended):
https://github.com/aegis-icons/aegis-icons/blob/master/SVG/AllMyLinks.svg

**For Aegis v1.4.2 and below**:
https://github.com/aegis-icons/aegis-icons/blob/master/PNG/AllMyLinks.png

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*
