### ISSUE TITLE
Icon request: Toontown Rewritten

### ISSUE THREAD

**Issue by joshcancode** [aegis-icons/aegis-icons#287]
- URL of the site or app **(required):** https://www.toontownrewritten.com/
- Logo resources for the icon **(optional, but recommended):** https://www.toontownrewritten.com/help/press

**Comment by krisu5** [comment]
Here you go!

**For Aegis v2.0 and above** (recommended):
https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Toontown%20Rewritten.svg
https://github.com/aegis-icons/aegis-icons/blob/master/SVG/.Variations/Toontown%20Rewritten%20fg.var.svg

**For Aegis v1.4.2 and below**:
https://github.com/aegis-icons/aegis-icons/blob/master/PNG/Toontown%20Rewritten.png
https://github.com/aegis-icons/aegis-icons/blob/master/PNG/Variations/Toontown%20Rewritten%20fg.var.png

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*
