### ISSUE TITLE
Icon request: VLC Player (GitLab forum for issues)

### ISSUE THREAD

**Issue by OmlineEditor** [aegis-icons/aegis-icons#289]
- URL of the site or app:  https://code.videolan.org/explore/projects/starred
- Logo resources for the icon: [vlc.zip](https://github.com/aegis-icons/aegis-icons/files/6794129/vlc.zip)

example of an icon in a zip file. maybe you will find better.

**Comment by krisu5** [comment]
If software is Gitlab, then it's kinda pointless to make a icon for specifically VLC gits.

**Comment by OmlineEditor** [comment]
> If software is Gitlab, then it's kinda pointless to make a icon for specifically VLC gits.

this is not gitlab. This is a separate site, you can see it. there is only a backend from gitlab. it's like a wordpress to create a website

**Comment by krisu5** [comment]
It still is GitLab by software.

I consider this as issue guideline's **section 6** kind of thing: https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines

Also see #174 for similar case.

It also could be misleading for users to have VLC icon in the pack (similar case: #94)

**Comment by OmlineEditor** [comment]
ok, then I will add this icon only for my phone.
