### ISSUE TITLE
Icon request: CoinTracking

### ISSUE THREAD

**Issue by HelmesPaul** [aegis-icons/aegis-icons#291]
- URL of the site or app **(required):** https://cointracking.info
- Logo resources for the icon **(optional, but recommended):** 

thank you

**Comment by krisu5** [comment]
Here you go!

**For Aegis v2.0 and above** (recommended):
https://github.com/aegis-icons/aegis-icons/blob/master/SVG/CoinTracking.svg

**For Aegis v1.4.2 and below**:
https://github.com/aegis-icons/aegis-icons/blob/master/PNG/CoinTracking.png

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*
