### ISSUE TITLE
Update icon: Bitwala

### ISSUE THREAD

**Issue by HelmesPaul** [aegis-icons/aegis-icons#292]
- URL of the site or app **(required):** https://bitwala.com/ now https://nuri.com/
- Reason for update **(required):** changed brand name and logo
- Logo resources for the icon **(optional, but recommended):**

**Comment by krisu5** [comment]
Has already updated:
https://aegis-icons.github.io/icons/primary/Nuri.svg
https://aegis-icons.github.io/icons/variations/Nuri%20bg.var.svg

Please check the [site](https://aegis-icons.github.io/) first before making issues.
