### ISSUE TITLE
Icon request: Firefly III

### ISSUE THREAD

**Issue by rubenelshof** [aegis-icons/aegis-icons#294]
- URL of the site or app **(required):** Firefly (https://www.firefly-iii.org/)
- Logo resources for the icon **(optional, but recommended):** 
https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/logo/

**Comment by krisu5** [comment]
Just in case, since author wants to, I'll have to ask permission first for modifying logo to monochrome.

**Comment by krisu5** [comment]
Got the permission.

**For Aegis v2.0 and above** (recommended):
https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Firefly%20III.svg

**For Aegis v1.4.2 and below**:
https://github.com/aegis-icons/aegis-icons/blob/master/PNG/Firefly%20III.png

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*
