### ISSUE TITLE
Icon request: Neowin (forum)

### ISSUE THREAD

**Issue by kolappannathan** [aegis-icons/aegis-icons#296]
- URL of the site or app **(required):** https://www.neowin.net/
- Logo resources for the icon **(optional, but recommended):** 

Neowin Forum login support 2FA for their accounts. Would be nice to have their icon.

**Comment by krisu5** [comment]
Usually I don't make icons for specific forum communities (mostly for forum softwares), but Neowin seems to be popular enough based of Alexa rank and total forum post / member count.

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Neowin.svg

Neowin's forum is powered by "Invision Community" forum software, so I also made icon for that too:

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Invision%20Community.svg

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

**Comment by kolappannathan** [comment]
@krisu5 Thank you.
