### ISSUE TITLE
Icon request: Report URI

### ISSUE THREAD

**Issue by kolappannathan** [aegis-icons/aegis-icons#297]
- URL of the site or app **(required):** https://report-uri.com/
- Logo resources for the icon **(optional, but recommended):** 

It is a tool I use to monitor Security Headers in my website and it supports 2FA.

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Report%20URI.svg

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*
