### ISSUE TITLE
Icon request: Opalstack

### ISSUE THREAD

**Issue by suksit** [aegis-icons/aegis-icons#299]
- URL of the site or app **(required):** https://www.opalstack.com/
- Logo resources for the icon **(optional, but recommended):**

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Opalstack.svg
https://github.com/aegis-icons/aegis-icons/blob/master/SVG/.Variations/Opalstack%20bg.var.svg

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*
