### ISSUE TITLE
Icon request: MyHeritage

### ISSUE THREAD

**Issue by nichu42** [aegis-icons/aegis-icons#30]
- URL of the site or app **(required):** https://www.myheritage.com/
- Logo resources for the icon **(optional, but recommended):** https://media.myheritage.com/wp-content/uploads/2016/11/MH_logo_RGB.jpg
- Hex color of the main brand color **(optional):**

**Comment by krisu5** [comment]
Media kit: https://media.myheritage.com/

**Comment by krisu5** [comment]
Done!

https://github.com/krisu5/aegis-icons/blob/master/PNG/MyHeritage.png
