### ISSUE TITLE
Icon request: Name.com

### ISSUE THREAD

**Issue by suksit** [aegis-icons/aegis-icons#300]
- URL of the site or app **(required):** https://www.name.com/
- Logo resources for the icon **(optional, but recommended):**

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Name.com.svg

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*
