### ISSUE TITLE
Icon request: Aternos.org

### ISSUE THREAD

**Issue by u8Jj3** [aegis-icons/aegis-icons#301]
- URL of the site or app **(required):** https://aternos.org
- Logo resources for the icon **(optional, but recommended):** https://aternos.gmbh/en/branding

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Aternos.svg

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*
