### ISSUE TITLE
Icon request: Splashtop

### ISSUE THREAD

**Issue by AbramTTP** [aegis-icons/aegis-icons#302]
- URL of the site or app: https://www.splashtop.com/
- Logo resources for the icon **Unavailable on website, but monocolor icon exists**

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Splashtop.svg

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*
