### ISSUE TITLE
Icon request: Bitpay

### ISSUE THREAD

**Issue by AbramTTP** [aegis-icons/aegis-icons#303]
- URL of the site or app **(required):** https://bitpay.com/
- Logo resources for the icon **(optional, but recommended):** https://brand.bitpay.com/7b6hnbyxw/v/0/p/21e903-brand-mark
- See color under usage section in the URL above too for exact HEX values

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Bitpay.svg

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*
