### ISSUE TITLE
Icon request: Fusang

### ISSUE THREAD

**Issue by AbramTTP** [aegis-icons/aegis-icons#304]
- URL of the site or app **(required):** https://www.fusang.co/
- Logo resources for the icon **(optional, but recommended):** No official page, but the official color is the yellow they use above.

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Fusang.svg

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*
