### ISSUE TITLE
Icon request: Kee Community Forum

### ISSUE THREAD

**Issue by AbramTTP** [aegis-icons/aegis-icons#305]
- URL of the site or app **(required):** https://forum.kee.pm/about
- Logo resources for the icon **(optional, but recommended):** No official media page
- This forum is for a KeePass Password Manager's Kee Extension, which allows autofilling of passwords on browsers.

**Comment by krisu5** [comment]
Rejected because of [issue guideline #6](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines).

Use one of the **Discourse** icons (forum software that Kee forum uses).
