### ISSUE TITLE
Icon request: AppVeyor

### ISSUE THREAD

**Issue by Otiel** [aegis-icons/aegis-icons#31]
- URL of the site or app: https://www.appveyor.com
- Logo resources for the icon: https://en.wikipedia.org/wiki/File:Appveyor_logo.svg

![image](https://user-images.githubusercontent.com/3851902/69327173-58cbfc80-0c4d-11ea-8183-d850c3b04721.png)

**Comment by krisu5** [comment]
Here's the icon:

https://github.com/krisu5/aegis-icons/blob/master/PNG/AppVeyor.png

**Comment by Otiel** [comment]
Thanks!
