### ISSUE TITLE
Icon submission: Zerodha

### ISSUE THREAD

**Issue by sreeragag7** [aegis-icons/aegis-icons#310]
- [x] I have read and followed CONTRIBUTING document.
- URL of the site or app **(required, unless it's generic icon):**  https://zerodha.com/
- Where did you took the BG color(s) **(required, unless it's generic icon):** Used logo color https://zerodha.com/

Uploaded files:
[Zerodha.zip](https://github.com/aegis-icons/aegis-icons/files/6949256/Zerodha.zip)

**Comment by krisu5** [comment]
Added to the repo! 👍
