### ISSUE TITLE
Icon request:Termius 

### ISSUE THREAD

**Issue by Midou36O** [aegis-icons/aegis-icons#311]
- URL of the site or app **(required):** : https://www.termius.com/
- Logo resources for the icon **(optional, but recommended):** 
[termius-icon@4x](https://user-images.githubusercontent.com/45198486/128641741-984e4ca8-11ca-4201-8d5e-b293512c8b60.png)
(Can be found [here](https://www.termius.com/brand-resources))

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Termius.svg

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*
