### ISSUE TITLE
Icon request: EuroDNS

### ISSUE THREAD

**Issue by ghost** [aegis-icons/aegis-icons#312]
Please add the logo for EuroDNS:
- URL https://www.eurodns.com/
- Logo resources https://www.eurodns.com/brand-assets

Thanks

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/EuroDNS.svg

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*
