### ISSUE TITLE
Icon request: Paycor

### ISSUE THREAD

**Issue by drinkcoffee247** [aegis-icons/aegis-icons#314]
- URL of the site or app **(required):** https://www.paycor.com/
- Logo resources for the icon **(optional, but recommended):**

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Paycor.svg

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*
