### ISSUE TITLE
Icon request: Cloudamo.com

### ISSUE THREAD

**Issue by ssancese** [aegis-icons/aegis-icons#315]
- URL of the site or app **(required):** www.cloudamo.com
- Logo resources for the icon **(optional, but recommended):**

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Cloudamo.svg

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

**Comment by ssancese** [comment]
Thanks Kristian!

Il dom 15 ago 2021, 00:49 Kristian Salonen ***@***.***> ha
scritto:
