### ISSUE TITLE
Icon request: Amazon Web Services

### ISSUE THREAD

**Issue by ssancese** [aegis-icons/aegis-icons#316]
- URL of the site or app **(required):** https://aws.amazon.com/
- Logo resources for the icon **(optional, but recommended):**

**Comment by krisu5** [comment]
Already exists with "AWS" acronym:
https://github.com/aegis-icons/aegis-icons/blob/master/SVG/AWS.svg
https://github.com/aegis-icons/aegis-icons/blob/master/SVG/.Variations/AWS%20bg.var.svg
