### ISSUE TITLE
Icon request: Oculus

### ISSUE THREAD

**Issue by SteffoSpieler** [aegis-icons/aegis-icons#317]
- URL of the site or app **(required):** https://www.oculus.com/
- Logo resources for the icon **(optional, but recommended):**

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Oculus.svg
https://github.com/aegis-icons/aegis-icons/blob/master/SVG/.Variations/Oculus%20bg.var.svg

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*
