### ISSUE TITLE
Icon request: Gandi

### ISSUE THREAD

**Issue by Otiel** [aegis-icons/aegis-icons#32]
- URL of the site or app: https://www.gandi.net 
- Logo resources for the icon: https://en.wikipedia.org/wiki/File:GandiSAS.svg

![image](https://user-images.githubusercontent.com/3851902/69327023-28845e00-0c4d-11ea-8c4a-c2d59f0a56ea.png)

**Comment by krisu5** [comment]
Done!

https://github.com/krisu5/aegis-icons/blob/master/PNG/Gandi.png

**Comment by Otiel** [comment]
Thanks!
