### ISSUE TITLE
Icon request: Minehub.de

### ISSUE THREAD

**Issue by SteffoSpieler** [aegis-icons/aegis-icons#320]
- URL of the site or app **(required):** https://minehub.de/
- Logo resources for the icon **(optional, but recommended):** https://minehub.de/static/web/img/logo/MHUB.svg

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Minehub.de.svg

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*
