### ISSUE TITLE
Icon request: CalorieTracker.io

### ISSUE THREAD

**Issue by drinkcoffee247** [aegis-icons/aegis-icons#321]
CalorieTracker.io

- URL of the site or app **(required):** https://calorietracker.io/
- Logo resources for the icon **(optional, but recommended):**

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/CalorieTracker.io.svg

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*
