### ISSUE TITLE
Icon request: Uphold

### ISSUE THREAD

**Issue by navharsh** [aegis-icons/aegis-icons#324]
- URL of the site or app **(required):** https://uphold.com/
- Logo resources for the icon **(optional, but recommended):**

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Uphold.svg

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*
