### ISSUE TITLE
Icon request: All-Inkl.com

### ISSUE THREAD

**Issue by Wyrrrd** [aegis-icons/aegis-icons#326]
- URL of the site or app **(required):** https://all-inkl.com/
- Logo resources for the icon **(optional, but recommended):** https://all-inkl.com/img/presse/ALL-INKL_LOGO_300DPI.jpg (best I could find...)

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/All-Inkl.svg

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*
