### ISSUE TITLE
Icon request: PeerTube

### ISSUE THREAD

**Issue by d4f5409d** [aegis-icons/aegis-icons#331]
- URL of the site or app **(required):** https://joinpeertube.org
- Logo resources for the icon **(optional, but recommended):**

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/PeerTube.svg

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*
