### ISSUE TITLE
Icon request: Lemmy

### ISSUE THREAD

**Issue by d4f5409d** [aegis-icons/aegis-icons#332]
- URL of the site or app **(required):** https://join-lemmy.org/
- Logo resources for the icon **(optional, but recommended):**

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Lemmy.svg
https://github.com/aegis-icons/aegis-icons/blob/master/SVG/.Variations/Lemmy%20bg.var.svg

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

**Comment by julianfairfax** [comment]
Lemmy has 2FA now: https://github.com/LemmyNet/lemmy/commit/30b38cc564994e8bd23fdce5844fc39323818dc5. Can you undo https://github.com/aegis-icons/aegis-icons/commit/de6490ef153486e3a80ea2becf1f3346ba55e15e?

**Comment by krisu5** [comment]
> Lemmy has 2FA now: https://github.com/LemmyNet/lemmy/commit/30b38cc564994e8bd23fdce5844fc39323818dc5. Can you undo https://github.com/aegis-icons/aegis-icons/commit/de6490ef153486e3a80ea2becf1f3346ba55e15e?

It's in the todos: https://github.com/aegis-icons/aegis-icons/projects/1#card-88451131

[I have lot more do to before adding this back though](https://github.com/aegis-icons/aegis-icons/issues/863).

**Comment by d4f5409d** [comment]
Bruh

**Comment by krisu5** [comment]
> Bruh

You asked the icon when it didn't have any 2FA support, so yeah, that's why it was removed before. The 2FA feature was actually released 2 years after this request.

I did requests blindly before double-checking that they had 2FA, because I trusted people. But after this one and many others, rules changed.

**Comment by d4f5409d** [comment]
Understandable. Let me joke on this one: I've seen the future, I was only too soon! Haha 😎
