### ISSUE TITLE
Icon request: Filen

### ISSUE THREAD

**Issue by drinkcoffee247** [aegis-icons/aegis-icons#333]
Filen

- URL of the site or app **(required):** https://filen.io
- Logo resources for the icon **(optional, but recommended):**

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Filen.svg
https://github.com/aegis-icons/aegis-icons/blob/master/SVG/.Variations/Filen%20bg.var.svg

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*
