### ISSUE TITLE
Icon request: Envato

### ISSUE THREAD

**Issue by acolombo11** [aegis-icons/aegis-icons#334]
- URL of the site or app: https://themeforest.net/, https://codecanyon.net/, https://videohive.net/, https://audiojungle.net/, etc. 
- Logo resources for the icon: https://jasonjun-envato.github.io/envato-design-resources/

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Envato.svg

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*
