### ISSUE TITLE
Icon request: Rstudio (forum)

### ISSUE THREAD

**Issue by Mazino-Urek** [aegis-icons/aegis-icons#335]
- URL of the site or app **(required):** https://community.rstudio.com/
- Logo resources for the icon **(optional, but recommended):** https://www.rstudio.com/about/logos/

**Comment by krisu5** [comment]
Rejected because of [issue guideline #6](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines)

Use one of the **Discourse** icons (forum software that this forum uses).
