### ISSUE TITLE
Icon request: Canapii

### ISSUE THREAD

**Issue by nichu42** [aegis-icons/aegis-icons#336]
- URL of the site or app **(required):** https://www.canapii.com/
- Logo resources for the icon **(optional, but recommended):** https://twitter.com/CanapiiOfficial/photo

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Canapii.svg

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

*P.S. Please do not add logo resources that don't fill the requirements writted in the issue template*
