### ISSUE TITLE
Icon request: Wordfence

### ISSUE THREAD

**Issue by nichu42** [aegis-icons/aegis-icons#337]
- URL of the site or app **(required):** https://www.wordfence.com/
- Logo resources for the icon **(optional, but recommended):** https://www.wordfence.com/wp-content/themes/wordfence/img/wordfence-medallion.png

**Comment by krisu5** [comment]
Here's the icon

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Wordfence.svg

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

*P.S. Please do not add logo resources that don't fill the requirements writted in the issue template*
