### ISSUE TITLE
Icon request: BnkToTheFuture

### ISSUE THREAD

**Issue by Sami32** [aegis-icons/aegis-icons#338]
- https://bnktothefuture.com/
- https://bnktothefuture.com/wp-content/themes/bttf/assets/img/logo-white.svg
- https://pbs.twimg.com/profile_images/1888762025/BF_LOW_RES_400x400.png

**Comment by krisu5** [comment]
Done!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/BnkToTheFuture.svg

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*
