### ISSUE TITLE
Icon request: WeTransfer

### ISSUE THREAD

**Issue by EinfachRuwen** [aegis-icons/aegis-icons#339]
- URL of the site or app **(required)**: https://wetransfer.com
- Logo resources for the icon **(optional, but recommended)**: https://upload.wikimedia.org/wikipedia/commons/2/27/WeTransfer_Logo.png

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/WeTransfer.svg
https://github.com/aegis-icons/aegis-icons/blob/master/SVG/.Variations/WeTransfer%20bg.var.svg

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

*P.S. Please do not add logo resources that don't fill the requirements writted in the issue template*
