### ISSUE TITLE
Icon request: Arduino

### ISSUE THREAD

**Issue by SteffoSpieler** [aegis-icons/aegis-icons#340]
- URL of the site or app **(required):** https://www.arduino.cc/
- Logo resources for the icon **(optional, but recommended):** https://cdn.arduino.cc/header-footer/prod/assets/headerLogo-arduino.svg

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Arduino.svg

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*
