### ISSUE TITLE
Icon request: Nexon

### ISSUE THREAD

**Issue by Trung0246** [aegis-icons/aegis-icons#342]
- URL of the site or app **(required):** http://nexon.com/
- Logo resources for the icon **(optional, but recommended):** http://company.nexon.com/Company/Introduce/NexonCI/CI.aspx

Same as https://github.com/aegis-icons/aegis-icons/issues/341, Nexon only have 1000px version.

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Nexon.svg

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*
