### ISSUE TITLE
Icon request: Runbox

### ISSUE THREAD

**Issue by nzgha** [aegis-icons/aegis-icons#343]
- URL of the site or app **(required):** https://runbox.com/
- Logo resources for the icon **(optional, but recommended):** https://github.com/runbox/runbox7/tree/master/src/assets https://community.runbox.com/

The icon at their community site was the cleanest high resolution logo I could find, although it seems they cut out the X at the bottom right a little bit.

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Runbox.svg

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*
