### ISSUE TITLE
Icon request: bitFlyer

### ISSUE THREAD

**Issue by ghost** [aegis-icons/aegis-icons#344]
- URL of the site or app **(required):** https://bitflyer.com/en-jp/
- Logo resources for the icon **(optional, but recommended):** [SVG](https://bitflyer.com/pub/common/top/bitflyer_logo.svg)

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/bitFlyer.svg

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*
