### ISSUE TITLE
Icon request: Monex

### ISSUE THREAD

**Issue by ghost** [aegis-icons/aegis-icons#345]
- URL of the site or app **(required):** https://www.monex.co.jp/
- Logo resources for the icon **(optional, but recommended):** [PNG](https://info.monex.co.jp/image/common/ico_monex_large.png)

**Comment by ghost** [comment]
English Page: https://info.monex.co.jp/company/english.html

**Comment by krisu5** [comment]
Press PDF with vector logo: https://www.monexgroup.jp/en/investor/ir_library/annual_report/main/00/teaserItems1/00/linkList/01/link/E_MONEX02.pdf

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Monex,%20Inc.svg

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*
