### ISSUE TITLE
Icon request: Aozora Securities

### ISSUE THREAD

**Issue by ghost** [aegis-icons/aegis-icons#346]
- URL of the site or app **(required):** https://www.aozora-sec.co.jp/
- Logo resources for the icon **(optional, but recommended):** [PNG](https://www.aozorabank.co.jp/ogp.png)

**Comment by krisu5** [comment]
SVG: https://www.aozora-sec.co.jp/assets/img/common/header/header_logo.svg

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Aozora%20Securities.svg

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*
