### ISSUE TITLE
Icon request: Osaka University

### ISSUE THREAD

**Issue by ghost** [aegis-icons/aegis-icons#347]
- URL of the site or app **(required):** https://www.osaka-u.ac.jp/en/
- Logo resources for the icon **(optional, but recommended):** [JPEG](https://www.osaka-u.ac.jp/kitei/reiki_honbun/u035RG00000082.html), [GIF](https://derma.med.osaka-u.ac.jp/etc/rogo/OUrogo.html)

**Comment by krisu5** [comment]
SVG: https://en.wikipedia.org/wiki/File:Osaka_University_logo.svg

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Osaka%20University.svg

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*
