### ISSUE TITLE
Icon request: HackerOne

### ISSUE THREAD

**Issue by ghost** [aegis-icons/aegis-icons#348]
- URL of the site or app **(required):** https://www.hackerone.com/
- Logo resources for the icon **(optional, but recommended):** [PNG](https://www.hackerone.com/sites/default/files/2017-06/HackerOne%20-%20short.png), [PDF](https://www.hackerone.com/sites/default/files/2017-06/HackerOne%20-%20short.pdf), [SVG(Logotype)](https://www.hackerone.com/themes/hacker_one/images/logo-hackerone.svg)

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/HackerOne.svg

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*
