### ISSUE TITLE
Icon request: Bugcrowd

### ISSUE THREAD

**Issue by ghost** [aegis-icons/aegis-icons#349]
- URL of the site or app **(required):** https://www.bugcrowd.com/
- Logo resources for the icon **(optional, but recommended):** [SVG](https://www.bugcrowd.com/wp-content/themes/bugcrowd-2019/includes/img/favicon/safari-pinned-tab.svg), [PNG](https://www.bugcrowd.com/wp-content/themes/bugcrowd-2019/includes/img/favicon/apple-touch-icon.png)

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Bugcrowd.svg

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*
