### ISSUE TITLE
Icon request: Floatplane

### ISSUE THREAD

**Issue by ukanuk** [aegis-icons/aegis-icons#35]
- URL of the site or app **(required):** 
  - https://www.floatplane.com
- Logo resources for the icon **(optional, but recommended):** 
   - https://frontend.floatplanecdn.com/2.14.2/assets/images/logos/floatplane/logo-blue.svg
   - https://frontend.floatplanecdn.com/2.14.2/assets/images/logos/floatplane/logo-blue.svg
- Hex color of the main brand color **(optional):**
  - **00aeef** is the HTML color code used in that logo file, not sure if that's what you're looking for? Floatplane also uses a lot of white (ffffff)

**Comment by ukanuk** [comment]
Not sure whether copyright allows use of this icon? If not I fully understand. A form to contact them is available at https://www.floatplane.com/support if you want, or emailing *support* at their domain floatplane.com also works. 

https://www.floatplane.com/legal/terms
Floatplane, including all content provided on Floatplane, whether or not such content is provided by Floatplane Media or a third-party, is protected by copyright, trade secret or other intellectual property laws and treaties. You may not use, reproduce, distribute, perform, publicly display or prepare derivative works of our content unless we give you permission in writing. You agree to use the service in accordance with all applicable laws, rules and regulations, or other restrictions on use of the service or Content on the website. You shall not archive, download (caching excepted), reproduce, distribute, modify, display, perform, publish, license, create derivative works from or otherwise infringe on, offer for sale, or use (except as explicitly stated herein) the content and information contained on or obtained from or through the service without prior permission from Floatplane Media or the Creator, as applicable.

**Comment by krisu5** [comment]
I contacted the support, based on that I make the icon or not.

Usually I make these logo based icons with "benefit of the doubt", even if it would be technically illegal. And if companies want, they can ask to takedown icon(s) as mentioned on bottom of README.

In my understanding, projects like [Simple Icons](https://github.com/simple-icons/simple-icons) don't ask permissions for logos from trademark owners. Also they are hosting [SVG of Floatplane's logo](https://simpleicons.org/icons/floatplane.svg).

But I made a exception this time, it would interesting to see what they think of using logos in project like this.

**Comment by krisu5** [comment]
Got a permission.

**Comment by krisu5** [comment]
Here's the icon:

https://github.com/krisu5/aegis-icons/blob/master/PNG/Floatplane.png

Happy 2020!

**Comment by ukanuk** [comment]
Looks good, thank you! Happy new year!
