### ISSUE TITLE
Icon request: M1 Finance

### ISSUE THREAD

**Issue by Efocat** [aegis-icons/aegis-icons#350]
- URL of the site or app **(required):** https://www.m1finance.com/
- Logo resources for the icon **(optional, but recommended):** [SVG](https://www.m1finance.com/wp-content/themes/theme-m1/public/images/logos/m1-logo-dark.svg)

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/M1%20Finance.svg

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*
