### ISSUE TITLE
Icon request: Yotta

### ISSUE THREAD

**Issue by Efocat** [aegis-icons/aegis-icons#351]
- URL of the site or app **(required):** https://www.withyotta.com/
- Logo resources for the icon **(optional, but recommended):** [PNG](https://s3-eu-west-1.amazonaws.com/tpd/logos/5f5ba2f56c8f190001dc5b74/0x0.png)

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Yotta.svg

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*
