### ISSUE TITLE
Icon request: Hiven

### ISSUE THREAD

**Issue by EinfachRuwen** [aegis-icons/aegis-icons#352]
- URL of the site or app **(required)**: https://hiven.io
- Logo resources for the icon **(optional, but recommended)**: https://hiven.io/static/media/logo.f7ff647e.svg

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Hiven.svg

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*
