### ISSUE TITLE
Icon request: TheraKey

### ISSUE THREAD

**Issue by EinfachRuwen** [aegis-icons/aegis-icons#353]
- URL of the site or app **(required)**: https://www.therakey.de
- Logo resources for the icon **(optional, but recommended)**: https://www.therakey.de/.resources/base-lightmodule/webresources/img/logo_sm.svg

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/TheraKey.svg

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*
