### ISSUE TITLE
Icon request: MC-HOST24

### ISSUE THREAD

**Issue by EinfachRuwen** [aegis-icons/aegis-icons#354]
- URL of the site or app **(required)**: https://mc-host24.de
- Logo resources for the icon **(optional, but recommended)**: https://mc-host24.de/assets/img/logo/140px-mc-host24-logo.png

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/MC-HOST24.svg

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*
