### ISSUE TITLE
Icon request: YNAB

### ISSUE THREAD

**Issue by ukanuk** [aegis-icons/aegis-icons#36]
- URL of the site or app **(required):** 
  - https://www.youneedabudget.com
- Logo resources for the icon **(optional, but recommended):** 
   - https://www.youneedabudget.com/press/
   - Download presskit, see Logos/ynab-logos-03.png
- Hex color of the main brand color **(optional):**
  - **85C3E9** is the HTML color code used in that logo file, not sure if that's what you're looking for?

**Comment by krisu5** [comment]
Done: https://github.com/krisu5/aegis-icons/blob/master/PNG/You%20Need%20A%20Budget.png

**Comment by ukanuk** [comment]
Thank you, that one definitely works. 

However, I had been expecting an icon using their logo rather than the stylized YNAB company name. If you have the desire/time, maybe this one could be an alternate version? Note that it's the webpage favicon and also the app icon they use, though after giving their website a second look I can definitely see that it's not immediately obvious from their main website. 

This image is from https://www.youneedabudget.com/press/, from the folder `Logos/ynab-logos-03.png`:
![image](https://user-images.githubusercontent.com/59303202/71669990-e143ce00-2db1-11ea-81b8-16d4062ec02f.png)

**Comment by krisu5** [comment]
I didn't notice that one, I ignored the press kit because it was just PNGs :stuck_out_tongue:

Luckily, there's Safari pinned tab SVG. I updated it.

EDIT: and added previous one as alt.

**Comment by ukanuk** [comment]
Looks great, thank you! 😊
