### ISSUE TITLE
Icon request: Jetbrains

### ISSUE THREAD

**Issue by wvffle** [aegis-icons/aegis-icons#38]
- URL of the site or app **(required):** https://www.jetbrains.com/

**Comment by krisu5** [comment]
Logo resources: https://www.jetbrains.com/company/brand/logos/

**Comment by krisu5** [comment]
Done!

https://raw.githubusercontent.com/krisu5/aegis-icons/master/PNG/JetBrains.png
https://raw.githubusercontent.com/krisu5/aegis-icons/master/PNG/Variations/JetBrains%20bg.var.png
