### ISSUE TITLE
Icon request: Black Desert Online

### ISSUE THREAD

**Issue by wvffle** [aegis-icons/aegis-icons#39]
- URL of the site or app **(required):** https://www.blackdesertonline.com

**Comment by krisu5** [comment]
Official vector found by a miracle, uploading it here just in case (maybe someone googling finds this useful).

[BDO_logo.zip](https://github.com/krisu5/aegis-icons/files/4074237/BDO_logo.zip)

**Comment by krisu5** [comment]
Here's the icons.

With original logo:
https://raw.githubusercontent.com/krisu5/aegis-icons/master/PNG/Black%20Desert%20Online.png
https://raw.githubusercontent.com/krisu5/aegis-icons/master/PNG/Variations/Black%20Desert%20Online%20bg.var.png

Alts with logo modified more vertical (way better imo):
https://raw.githubusercontent.com/krisu5/aegis-icons/master/PNG/Variations/Black%20Desert%20Online%20alt.png
https://raw.githubusercontent.com/krisu5/aegis-icons/master/PNG/Variations/Black%20Desert%20Online%20alt%20bg.var.png
