### ISSUE TITLE
Icon request: Fanduel

### ISSUE THREAD

**Issue by ASNosal** [aegis-icons/aegis-icons#390]
- URL of the site or app **(required):**  https://www.fanduel.com
- Logo resources for the icon **(optional, but recommended):**

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/FanDuel.svg

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*
