### ISSUE TITLE
Icon request: Authelia

### ISSUE THREAD

**Issue by aleksandarmomic** [aegis-icons/aegis-icons#391]
- URL of the site or app: https://www.authelia.com/
- Logo resources for the icon: I didn't find the vector image nor a high resolution image, this is the closest I've found: https://avatars.githubusercontent.com/u/59122411

I regularly use Authelia and it would be nice to have an Icon for it in Aegis.

**Comment by aleksandarmomic** [comment]
I found a higher resolution https://ibracorp.io/content/images/size/w1750/2021/03/724ca480-396f-11ea-874f-d39c6900e14d-2.png

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Authelia.svg

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*
