### ISSUE TITLE
Icon request: Uptime Kuma

### ISSUE THREAD

**Issue by ghost** [aegis-icons/aegis-icons#403]
- URL of the site or app **(required):** https://github.com/louislam/uptime-kuma
- Logo resources for the icon **(optional, but recommended):** https://raw.githubusercontent.com/louislam/uptime-kuma/ff5f2e8dfb0822ba3642ed94ad8ff81da3256902/public/icon.svg

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Uptime%20Kuma.svg

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*
