### ISSUE TITLE
Icon request: mailgun

### ISSUE THREAD

**Issue by ghost** [aegis-icons/aegis-icons#404]
- URL of the site or app **(required):** https://www.mailgun.com/
- Logo resources for the icon **(optional, but recommended):** https://cdn.freebiesupply.com/logos/large/2x/mailgun-logo-png-transparent.png

**Comment by krisu5** [comment]
Already exists: https://aegis-icons.github.io/icons/primary/Mailgun.svg

Please search the site first before making requests.

**Comment by ghost** [comment]
Interesting. When I download the icon pack from https://aegis-icons.github.io/, Mailgun.svg is not included.

**Comment by krisu5** [comment]
Because as the link says, it's updated monthly.

Last update was 14 days ago, next comes around 7th of october (that includes Mailgun icon).
