### ISSUE TITLE
Icon request: Authentik

### ISSUE THREAD

**Issue by ghost** [aegis-icons/aegis-icons#405]
- URL of the site or app **(required):** https://goauthentik.io/
- Logo resources for the icon **(optional, but recommended):** https://github.com/goauthentik.png

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/authentik.svg

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*
