### ISSUE TITLE
Icon request: MXroute

### ISSUE THREAD

**Issue by ghost** [aegis-icons/aegis-icons#406]
- URL of the site or app **(required):** https://mxroute.com/
- Logo resources for the icon **(optional, but recommended):** https://is5-ssl.mzstatic.com/image/thumb/Purple114/v4/a0/f2/52/a0f252d1-e7cc-9f78-9659-0bccab772b42/source/256x256bb.jpg

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/MXroute.svg

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*
