### ISSUE TITLE
Icon request: Unraid

### ISSUE THREAD

**Issue by ghost** [aegis-icons/aegis-icons#407]
- URL of the site or app **(required):** https://unraid.net/
- Logo resources for the icon **(optional, but recommended):** http://www.testedtechnology.co.uk/wp-content/uploads/2020/12/UnRAID-Icon.png

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Unraid.svg

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*
