### ISSUE TITLE
Icon request: Migros

### ISSUE THREAD

**Issue by Schwitzd** [aegis-icons/aegis-icons#409]
- URL of the site or app **(required):** https://www.migros.ch
- Logo resources for the icon **(optional, but recommended):**

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Migros.svg

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*
