### ISSUE TITLE
Icon request: Manjaro Linux (forum)

### ISSUE THREAD

**Issue by hmlendea** [aegis-icons/aegis-icons#410]
- URL of the site or app **(required):** https://forum.manjaro.org/
- Logo resources for the icon **(optional, but recommended):** https://commons.wikimedia.org/wiki/File:Manjaro-logo.svg

**Comment by krisu5** [comment]
Closed because of [issue guideline #6](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines)

Use one of the **Discourse** icons (forum software this forum uses).
