### ISSUE TITLE
Icon request: INB.Network

### ISSUE THREAD

**Issue by Schwitzd** [aegis-icons/aegis-icons#411]
Can you please add the icon of INB.Network?

- URL of the site or app **(required):** https://auth.inb.network/

Cheers :)

**Comment by krisu5** [comment]
Sorry but I have to reject this.

Site is too vague with only the login screen and nothing else (sitenote: every thing in the Google says this is a scam, ofc I don't know for sure but it's not a good sign) and even then, the SVG of the logo featured in this website is actually low resolution PNG image.

There's generic icons you can use like `Money`, `Bitcoin` etc.
