### ISSUE TITLE
Icon request: Peerberry

### ISSUE THREAD

**Issue by angelosne** [aegis-icons/aegis-icons#412]
- URL of the site or app **(required):** https://peerberry.com/
- Logo resources for the icon **(optional, but recommended):**

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/PeerBerry.svg

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

**Comment by angelosne** [comment]
Thank you!
