### ISSUE TITLE
Icon request: Vauld

### ISSUE THREAD

**Issue by jerryn70** [aegis-icons/aegis-icons#413]
- URL of the site or app **(required):** https://www.vauld.com
- Logo resources for the icon **(optional, but recommended):**

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Vauld.svg

*P.S. Please use **Icon request (app / site)** issue template, it's easier for me and you.*

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*
