### ISSUE TITLE
Icon submission: Mutasibank

### ISSUE THREAD

**Issue by gnulab-id** [aegis-icons/aegis-icons#415]
- [ X ] I have read and followed CONTRIBUTING document.
- URL of the site or app **(required, unless it's generic icon):** 
- https://mutasibank.co.id/
- Where did you took the BG color(s) **(required, unless it's generic icon):** 
- website (https://mutasibank.co.id/)

Uploaded files:
[Mutasibank.zip](https://github.com/aegis-icons/aegis-icons/files/7440698/Mutasibank.zip)

**Comment by krisu5** [comment]
Added to the repo 👍
