### ISSUE TITLE
Icon submission: Niagahoster

### ISSUE THREAD

**Issue by gnulab-id** [aegis-icons/aegis-icons#416]
- [ X ] I have read and followed CONTRIBUTING document.
- URL of the site or app **(required, unless it's generic icon):** 
- https://www.niagahoster.co.id/
- Where did you took the BG color(s) **(required, unless it's generic icon):** 
- website (https://www.niagahoster.co.id/)

Uploaded files:

[Niagahoster.zip](https://github.com/aegis-icons/aegis-icons/files/7440710/Niagahoster.zip)

**Comment by krisu5** [comment]
Added to the repo 👍
