### ISSUE TITLE
Icon submission: Samtrade FX

### ISSUE THREAD

**Issue by gnulab-id** [aegis-icons/aegis-icons#417]
- [X] I have read and followed CONTRIBUTING document.
- URL of the site or app **(required, unless it's generic icon):** 
- https://www.samtradefx.com/
- Where did you took the BG color(s) **(required, unless it's generic icon):** 
- website (https://www.samtradefx.com/)

Uploaded files:
[SAM Trade.zip](https://github.com/aegis-icons/aegis-icons/files/7440726/SAM.Trade.zip)

**Comment by krisu5** [comment]
Added to the repo 👍
