### ISSUE TITLE
Icon submission: Tokocrypto

### ISSUE THREAD

**Issue by gnulab-id** [aegis-icons/aegis-icons#418]
- [X] I have read and followed CONTRIBUTING document.
- URL of the site or app **(required, unless it's generic icon):** 
- https://www.tokocrypto.com/
- Where did you took the BG color(s) **(required, unless it's generic icon):** 
- website (https://www.tokocrypto.com/)

Uploaded files:
[TokoCrypto.zip](https://github.com/aegis-icons/aegis-icons/files/7440742/TokoCrypto.zip)

**Comment by krisu5** [comment]
Added to the repo 👍
