### ISSUE TITLE
Icon Request: DreamFactory, Figma, H&R Block, NameSilo, TaxAct

### ISSUE THREAD

**Issue by pdhoopr** [aegis-icons/aegis-icons#43]
Hi there! 👋 

Love this set of icons and really appreciate your work here. Recently switched to Aegis and these are the only services I came across that didn't have an icon. Not sure if multiple requests in the same issue are okay; if not, I'm happy to make separate ones. Thank you!

## DreamFactory

- URL of the site or app **(required):**: https://www.dreamfactory.com/

## Figma
- URL of the site or app **(required):** https://www.figma.com

## H&R Block
- URL of the site or app **(required):** https://www.hrblock.com

## NameSilo
- URL of the site or app **(required):** https://www.namesilo.com

## TaxAct
- URL of the site or app **(required):** https://www.taxact.com

**Comment by krisu5** [comment]
Thanks! Yeah, it's OK to make multiple requests.

Here's the icons:
https://github.com/krisu5/aegis-icons/blob/master/PNG/DreamFactory.png
https://github.com/krisu5/aegis-icons/blob/master/PNG/Figma.png
https://github.com/krisu5/aegis-icons/blob/master/PNG/H%26R%20Block.png
https://github.com/krisu5/aegis-icons/blob/master/PNG/NameSilo.png
https://github.com/krisu5/aegis-icons/blob/master/PNG/TaxAct.png

**Comment by pdhoopr** [comment]
So awesome, thank you!
