### ISSUE TITLE
Icon request: Roblox

### ISSUE THREAD

**Issue by vepig** [aegis-icons/aegis-icons#437]
- URL of the site or app **(required):** https://www.roblox.com/
- Logo resources for the icon **(optional, but recommended):**

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Roblox.svg

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*
