### ISSUE TITLE
Icon request: Gentoo Linux

### ISSUE THREAD

**Issue by vepig** [aegis-icons/aegis-icons#438]
- URL of the site or app **(required):** https://www.gentoo.org/
- Logo resources for the icon **(optional, but recommended):**

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Gentoo%20Linux.svg

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*
