### ISSUE TITLE
Allow user selecting icon using app

### ISSUE THREAD

**Issue by ctron** [aegis-icons/aegis-icons#44]
To my understanding it still is an unresolved issue on how to easily add the images as profile icons to ageis.

I think a nice solution to this Problem could be, if this icon pack had its own app, which implements being an image source on Android. Currently aegis allows you to pick an icon, which triggers the standard Android source selection. Would this icon pack be "wrapped" in an app, people would be able to select an icon in aegis, triggering this wrapper app, and fetch store the icon in aegis.

**Comment by krisu5** [comment]
Unfortunately I don't have programming skills for that (and I have tried, it's not my thing). Only programming I do is batch files, HTML and CSS :P

Unless someone else wants to do it, then go for it. But I'm only designer, so I only do icons.

And note that Aegis will have better icon system someday as said by developers.
