### ISSUE TITLE
Icon request: Equinix

### ISSUE THREAD

**Issue by mmlb** [aegis-icons/aegis-icons#448]
- URL of the site or app **(required):** https://console.equinix.com
- Logo resources for the icon **(optional):** Logo set from https://brand.equinix.com/

Should be another easy one, but I can do it too if you'd like :D. Thanks.

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Equinix.svg

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

**Comment by mmlb** [comment]
Thanks again!
