### ISSUE TITLE
Icon request: Docker / DockerHub

### ISSUE THREAD

**Issue by Siosm** [aegis-icons/aegis-icons#45]
- URL of the site or app:
  - https://www.docker.com
  - https://hub.docker.com/
  - https://www.docker.com/blog/designing-docker-hub-2fa
- Logo resources for the icon:
  - https://simpleicons.org/icons/docker.svg
  - https://cdn.svgporn.com/logos/docker-icon.svg
  - https://worldvectorlogo.com/logo/docker
  - https://worldvectorlogo.com/logo/docker-1
- Hex color of the main brand color: #2496ed

Thanks for those great icons!

**Comment by krisu5** [comment]
Done: https://github.com/krisu5/aegis-icons/blob/master/PNG/Docker.png

**Comment by Siosm** [comment]
Awesome! Thanks!
