### ISSUE TITLE
Icon request: Home Assistant

### ISSUE THREAD

**Issue by ffidan61** [aegis-icons/aegis-icons#46]
- URL of the site or app **(required):** https://www.home-assistant.io/
- Logo resources for the icon **(optional, but recommended):** https://github.com/home-assistant/home-assistant-assets/blob/master/logo-round.svg

**Comment by krisu5** [comment]
Here you go:

https://github.com/krisu5/aegis-icons/blob/master/PNG/Home%20Assistant.png
