### ISSUE TITLE
Icon request: Nutstore

### ISSUE THREAD

**Issue by Vstory** [aegis-icons/aegis-icons#48]
Remember to add **name of the site or app** at the end of the title (you can delete this line if you want)

- URL of the site or app **(required):** [https://www.jianguoyun.com/](https://www.jianguoyun.com/)

**Comment by krisu5** [comment]
Logo SVGs:
http://www.iconarchive.com/show/papirus-apps-icons-by-papirus-team/nutstore-icon.html
https://icon-icons.com/icon/nutstore/94623
http://mirror.alpix.eu/deepin/lastore/metadata/nautilus-nutstore/meta/icons/
https://github.com/FoxAuth/FoxAuth/blob/master/src/icons/service/nutstore.svg

**Comment by krisu5** [comment]
Done!

https://github.com/krisu5/aegis-icons/blob/master/PNG/Nutstore.png

**Comment by Vstory** [comment]
> Done!
> 
> https://github.com/krisu5/aegis-icons/blob/master/PNG/Nutstore.png


Thank you.
