### ISSUE TITLE
Icon request: V2EX

### ISSUE THREAD

**Issue by Vstory** [aegis-icons/aegis-icons#49]
Remember to add **name of the site or app** at the end of the title (you can delete this line if you want)

- URL of the site or app **(required):** [V2EX](https://www.v2ex.com/)

**Comment by krisu5** [comment]
Logo SVGs:
https://github.com/lexrus/fontdiao/blob/master/svg/v2ex.svg
https://github.com/jaywcjlove/logo/blob/master/img/v2ex.svg (?)

**Comment by krisu5** [comment]
There's the icon with alts and variations:
https://github.com/krisu5/aegis-icons/blob/master/PNG/V2EX.png
https://github.com/krisu5/aegis-icons/blob/master/PNG/Variations/V2EX%20bg.var.png
https://github.com/krisu5/aegis-icons/blob/master/PNG/Variations/V2EX%20alt.png
https://github.com/krisu5/aegis-icons/blob/master/PNG/Variations/V2EX%20alt%20bg.var.png

**Comment by Vstory** [comment]
> There's the icon with alts and variations:


[https://github.com/krisu5/aegis-icons/blob/master/PNG/V2EX.png](https://github.com/krisu5/aegis-icons/blob/master/PNG/V2EX.png)
the best
