### ISSUE TITLE
Icon request: axe

### ISSUE THREAD

**Issue by pdhoopr** [aegis-icons/aegis-icons#50]
- URL of the site or app **(required): https://www.deque.com/axe

- Logo resources for the icon **(optional, but recommended):** https://gist.github.com/pdhoopr/3b0cc7c002be091de8d403ef3d64dfa0 (I plopped it in a gist for easier discoverability)

- Hex color of the main brand color **(optional):** #283640

**Comment by krisu5** [comment]
Here's the icons:
https://github.com/krisu5/aegis-icons/blob/master/PNG/axe.png
https://github.com/krisu5/aegis-icons/blob/master/PNG/Variations/axe%20bg.var.png

EDIT: thanks for the SVG btw, I don't know if I could have found it.
