### ISSUE TITLE
Icon request: Coding

### ISSUE THREAD

**Issue by Vstory** [aegis-icons/aegis-icons#51]
Remember to add **name of the site or app** at the end of the title (you can delete this line if you want)

- URL of the site or app **(required):** [Coding](https://coding.net/)
- Logo resources for the icon **(optional, but recommended):** [https://github.com/jaywcjlove/logo/blob/master/img/coding.svg](https://github.com/jaywcjlove/logo/blob/master/img/coding.svg)

**Comment by krisu5** [comment]
Done!
https://github.com/krisu5/aegis-icons/blob/master/PNG/CODING.png

BG variation for dark / AMOLED theme: https://github.com/krisu5/aegis-icons/blob/master/PNG/Variations/CODING%20bg.var.png
