### ISSUE TITLE
Icon request: Mailcow

### ISSUE THREAD

**Issue by albakham** [aegis-icons/aegis-icons#53]
- URL of the site or app **(required):** https://mailcow.email/

- Logo resources for the icon **(optional, but recommended):** https://github.com/mailcow/mailcow-dockerized/blob/master/data/web/img/cow_mailcow.svg

**Comment by krisu5** [comment]
Oh boy, that's challenge to make that logo into monochrome. I will try, but I don't promise that's gonna be 100% great result.

**Comment by krisu5** [comment]
This gave me lot of work , but it's done.

https://github.com/krisu5/aegis-icons/blob/master/PNG/Mailcow.png
