### ISSUE TITLE
Icon request: Proxmox

### ISSUE THREAD

**Issue by albakham** [aegis-icons/aegis-icons#54]
- URL of the site or app **(required):** https://www.proxmox.com/en/

- Logo resources for the icon **(optional, but recommended):** http://xor.meo.ws/7_ZZU61cI1fmO5qVcoJs0s92KRe2LNBU/pve.svg

**Comment by krisu5** [comment]
https://github.com/krisu5/aegis-icons/blob/master/PNG/Proxmox.png
