### ISSUE TITLE
Icon request: Young Platform

### ISSUE THREAD

**Issue by Rtype-SPC** [aegis-icons/aegis-icons#543]
### URL of the site or app

https://youngplatform.com

### Logo resources for the icon

https://storage.googleapis.com/young-documents/2019_Presskit_Smart.zip

### Anything else?

No response

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Young%20Platform.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
