### ISSUE TITLE
Icon request: IVPN

### ISSUE THREAD

**Issue by xlbrto** [aegis-icons/aegis-icons#57]
- URL of the site or app **https://www.ivpn.net/** 
- Logo resources for the icon **https://www.ivpn.net/press** 
- Hex color of the main brand color **HEX #FF3344**

**Comment by krisu5** [comment]
Here you go!

https://github.com/krisu5/aegis-icons/blob/master/PNG/IVPN.png
Alternative: https://github.com/krisu5/aegis-icons/blob/master/PNG/Variations/IVPN%20alt.png

**Comment by xlbrto** [comment]
Thank you!
