### ISSUE TITLE
Icon submission: CoinTracker

### ISSUE THREAD

**Issue by CampinCarl** [aegis-icons/aegis-icons#578]
### Icon type

Logo based

### URL of the site or app

https://www.cointracker.io/

### Logo / icon info

https://s3-us-west-1.amazonaws.com/coin-tracker-public/static/images/icons/logo_white.svg

### Background color info

Background color taken from the website's footer, which has the CoinTracker logo on a dark blue background.

![CoinTracker-Footer](https://user-images.githubusercontent.com/11837803/162577862-4032bc64-e109-42d9-9a54-5879c248c290.png)

1) CoinTracker `logo_white.svg` combination mark in the `#footer` div.
2) The `#footer` div's dark blue background color, i.e., `#03122e`.

### Upload icon(s)

CoinTracker Icon
:---:
![CoinTracker](https://user-images.githubusercontent.com/11837803/162578197-71a7554d-c7d3-4855-8eee-d5b8b126f063.png)
[CoinTracker.zip](https://github.com/aegis-icons/aegis-icons/files/8457096/CoinTracker.zip)

### Confirmation

- [X] I have read and **carefully** followed [CONTRIBUTING document](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md) during the creation of the icon.

**Comment by krisu5** [comment]
Brand colors are all over the place with this brand, but I think the header SVG ("no scroll" version) has more "correct" color: https://s3-us-west-1.amazonaws.com/coin-tracker-public/static/images/icons/logo_blue.svg

It's also better BG color for Amoled theme.

**Comment by CampinCarl** [comment]
That works for me—the blue in that file is `#0182ff`. Thank you for the feedback.

CoinTracker
:---:
![CloudTracker](https://user-images.githubusercontent.com/11837803/162589102-24f49283-9331-40a3-9a82-688503b6d771.png)
[CoinTracker.zip (v2)](https://github.com/aegis-icons/aegis-icons/files/8457641/CoinTracker.zip)

**Comment by krisu5** [comment]
Added to the repo!
