### ISSUE TITLE
Icon request: Linus Tech Tips Forum

### ISSUE THREAD

**Issue by vishalnandagopal** [aegis-icons/aegis-icons#58]
Linus Tech Tips Forum / LTT Forum

- URL of the site or app - https://www.linustechtips.com

- Logo resources for the icon 

You can choose which is better.
1. https://yt3.ggpht.com/a/AGF-l7_GPnSqhtxkf5pgDj4jdL3EfgJkG09iAXg3Og=s900-mo-c-c0xffffffff-rj-k-no 
2. https://upload.wikimedia.org/wikipedia/commons/7/77/2018_Linus_Tech_Tips_logo.svg

On a side note, is the resource/icon pack being developed to merge and make it a built in feature with the Aegis Authenticator app some time later?
 Or is it for the user to download and use as required, if he/she wants to?. ( If yes, can you please tell how to download and use? )

**Comment by ukanuk** [comment]
Concerning whether it will be built into Aegis, see the discussions already at https://github.com/beemdevelopment/Aegis/issues/63 and also more recently https://github.com/beemdevelopment/Aegis/pull/221. Devs are aware of the desire and plan to make it better, but aren't yet sure how it will all work.

A big plus for Aegis is that it does not require any network permissions (it runs completely offline and never asks Android/users for permission to connect to the internet). The easy answer is that icons should be baked into the app, but that's problematic because then a new version of Aegis has to be released every time there's a new icon, which isn't really worth the effort.

**Comment by vishalnandagopal** [comment]
An update for every 5-10 icons would be the ideal option, if the icons are being bundled with the app itself.
The best option would be to only update icons, and download the files from this very GitHub repo. Like how ad bockers update host files. Only icons are updated, not the entire app. But that means the app needs internet access permission, which is not really a problem, if a toggle is included in the settings.
Or create a icon folder in the app's storage to place all icons after manually downloading files as needed.

**Comment by krisu5** [comment]
Here's the icon for LTT: https://github.com/krisu5/aegis-icons/blob/master/PNG/Linus%20Tech%20Tips.png

> On a side note, is the resource/icon pack being developed to merge and make it a built in feature with the Aegis Authenticator app some time later?

Not at the currently. This is unofficial project still so even if new icon system is implemented, it's unsure if these icons are used.

> Or is it for the user to download and use as required, if he/she wants to?. ( If yes, can you please tell how to download and use? )

Best way IMO is:
1. [Download latest icon pack](https://github.com/krisu5/aegis-icons/releases/latest) (click to unhide the "Assets" section and download ZIP named as "PNGs_2020-04-03.zip").
  - This pack includes every icon currectly except: LTT, [IVPN](https://github.com/krisu5/aegis-icons/issues/57#issuecomment-609766101), [Porkbun](https://github.com/krisu5/aegis-icons/blob/master/PNG/Porkbun.png) and [fixed Brave icon](https://github.com/krisu5/aegis-icons/blob/master/PNG/Brave.png). If you want those, check the links and download those as PNG.
2. In the file manager, go to "Download" folder and unzip the ZIP (if you don't have file manager, I recommend [Amaze](https://play.google.com/store/apps/details?id=com.amaze.filemanager&hl=en_US))
3. In Aegis, edit 2FA account you want to add the icon.
4. In 2FA account edit, click circle that has one letter in it.
5. Select app for finding icon PNGs (like file manager or gallery app).
6. Go to folder where the icon PNGs are and select image you want.
7. After selecting the icon, there's **checkmark button** you have to press for confirming selected icon.
8. Click "Save"
9. Repeat steps 3 to 8 for other accounts.

> The best option would be to only update icons, and download the files from this very GitHub repo. Like how ad bockers update host files. Only icons are updated, not the entire app. But that means the app needs internet access permission, which is not really a problem, if a toggle is included in the settings.

Devs has stated that they want to keep the app as offline as possible for privacy reasons. They want to please the most paranoid users by providing 100% offline app. @ukanuk pretty much said what I have said in the past.
