### ISSUE TITLE
Icon request: Porkbun

### ISSUE THREAD

**Issue by ukanuk** [aegis-icons/aegis-icons#59]
- URL of the site or app **(required):** 
  - https://porkbun.com
- Logo resources for the icon **(optional, but recommended):** 
  - [**SVG Logo**](https://porkbun.com/partners/logos/porkbun.comphpPkl2eU.svg) from their homepage
  - Official branding page: https://porkbun.design

**Comment by krisu5** [comment]
Here you go!

https://github.com/krisu5/aegis-icons/blob/master/PNG/Porkbun.png
