### ISSUE TITLE
Icon request: Sophos

### ISSUE THREAD

**Issue by brunopereira7** [aegis-icons/aegis-icons#62]
URL of the site or app: https://www.sophos.com/
Logo resources for the icon: https://www.sophos.com/en-us/brand-guidelines/s-shield.aspx

**Comment by krisu5** [comment]
https://github.com/krisu5/aegis-icons/blob/master/PNG/Sophos.png
Alternative: https://github.com/krisu5/aegis-icons/blob/master/PNG/Variations/Sophos%20alt.png
