### ISSUE TITLE
Icon request: Fedora

### ISSUE THREAD

**Issue by holequantum** [aegis-icons/aegis-icons#620]
### URL for the brand / site / app

https://getfedora.org/

### Logo resources for the icon

https://upload.wikimedia.org/wikipedia/commons/4/41/Fedora_icon_%282021%29.svg

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Fedora.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*

**Comment by holequantum** [comment]
thanks.
