### ISSUE TITLE
Icon request: KDE

### ISSUE THREAD

**Issue by holequantum** [aegis-icons/aegis-icons#625]
### URL for the brand / site / app

https://kde.org/

### Logo resources for the icon

https://kde.org/stuff/clipart/

### Anything else?

kde and plasma both logos are already there on this link with svg and png and jpg

**Comment by krisu5** [comment]
We are not adding "Plasma" logo.

KDE already exists: https://aegis-icons.github.io/icons/primary/KDE.svg

**Comment by holequantum** [comment]
why not plasma

**Comment by krisu5** [comment]
Because we only make icons for main master brand.

**Comment by holequantum** [comment]
okey.
