### ISSUE TITLE
Update icon: Ubuntu

### ISSUE THREAD

**Issue by holequantum** [aegis-icons/aegis-icons#626]
### URL for the brand / site / app

https://ubuntu.com

### Reason for update

New logo

### Logo resources for the icon

https://design.ubuntu.com/downloads/

**Comment by holequantum** [comment]
https://design.ubuntu.com/downloads/

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Ubuntu.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*

**Comment by holequantum** [comment]
nice thanks.
