### ISSUE TITLE
Icon request: Flipkart

### ISSUE THREAD

**Issue by holequantum** [aegis-icons/aegis-icons#627]
### URL for the brand / site / app

https://www.flipkart.com/

**Comment by krisu5** [comment]
Okay seriously, please use proper capitalization for the brand name and **stop adding "logo" to the issue title!**

**Comment by holequantum** [comment]
sorry

**Comment by krisu5** [comment]
Based of [2FA Directory](https://2fa.directory/int/) and [this article](https://indianexpress.com/article/technology/tech-news-technology/why-you-need-to-have-two-factor-authentication-on-for-all-accounts-7379065/), there's no 2FA in Flipcart.
