### ISSUE TITLE
keepassXC logo

### ISSUE THREAD

**Issue by holequantum** [aegis-icons/aegis-icons#629]
### URL for the brand / site / app

https://keepassxc.org/

### Logo resources for the icon

https://app.codecov.io/gh/keepassxreboot/keepassxc

**Comment by krisu5** [comment]
No, that's not what I mean with title. There's intructions in the form that reads:

> ⚠️ Remember to **add name of the brand / site / app** at the end of "Icon request:" part on top, **do not change the formatting of the title!**

> Please use proper capitalization for the name (check the capitalization from their app / website).

Stop rushing at making the issues and **read.**

<sup>I'm already regretting of opening issues section...</sup>

**Comment by holequantum** [comment]
> No, that's not what I mean with title. There's intructions in the form that reads:
> 
> > ⚠️ Remember to **add name of the brand / site / app** at the end of "Icon request:" part on top, **do not change the formatting of the title!**
> 
> > Please use proper capitalization for the name (check the capitalization from their app / website).
> 
> Stop rushing at making the issues and **read.**
> 
> I'm already regretting of opening issues section...

okey.

**Comment by krisu5** [comment]
Rejected, KeepassXC doesn't support 2FA / TOTP for database protection.

Source: https://keepassxc.org/docs/#faq-yubikey-otp

> Q: But the feature list says KeePassXC supports TOTP. I am confused.
> A: We do support generation of timed one-time passwords (TOTP), but do not (and cannot) support it for securing your KeePassXC database.
