### ISSUE TITLE
Icon request: Codecov

### ISSUE THREAD

**Issue by holequantum** [aegis-icons/aegis-icons#631]
### URL for the brand / site / app

https://about.codecov.io/

**Comment by krisu5** [comment]
No 2FA with this either.

**Comment by holequantum** [comment]
> No 2FA with this either. I made account and checked myself.
> 
> If you ever gonna submit non-2FA related issue request again, I'll ban you. I know I have said that many times, but I mean it.

when i have added i don't know about that you only include services which have 2fa support.
and you no need to say thank i really don't want to spam i just want to have those svg icons but now i understand. you look at my other requests and i have shared there svg files also hence it will be easier for you to upload.
