### ISSUE TITLE
gitea logo

### ISSUE THREAD

**Issue by holequantum** [aegis-icons/aegis-icons#632]
### URL for the brand / site / app

https://gitea.io/en-us/

**Comment by krisu5** [comment]
This is final warning, you are banned at next duplicate issue. Stop rushing at making the issues. It seriously is pissing me off.

Already exists: https://aegis-icons.github.io/icons/primary/Gitea.svg

**Comment by holequantum** [comment]
sorry i actually did not find that some times ago my mistake. i will be careful
