### ISSUE TITLE
mullvad

### ISSUE THREAD

**Issue by holequantum** [aegis-icons/aegis-icons#634]
### URL for the brand / site / app

https://mullvad.net/en/

**Comment by krisu5** [comment]
Mullvad doesn't have 2FA.

**Comment by holequantum** [comment]
but we have ivpn.

**Comment by krisu5** [comment]
**Because IT has 2fa support!**

Do you even use Aegis?

**Comment by holequantum** [comment]
yes obviously and it is also very cool to have icons i have printed some icon on my laptop also having a icon is not something bad that is why i have requested.

**Comment by krisu5** [comment]
>  it is also very cool to have icons i have printed some icon on my laptop also having a icon is not something bad that is why i have requested.

We don't make icons for general purpose, we only focus on userbase of Aegis, the Android app.
