### ISSUE TITLE
Icon request: State Bank of India

### ISSUE THREAD

**Issue by holequantum** [aegis-icons/aegis-icons#636]
### URL for the brand / site / app

https://www.onlinesbi.com/

### Anything else?

it provides 2fa while login

**Comment by krisu5** [comment]
I'm banning you **if you don't start follow the proper issue title format already!**

It is:

> Icon request: BRAND_NAME_HERE

**Comment by krisu5** [comment]
Also, I wish also that you stop making issues for awhile, until requested icons are done.

**Comment by holequantum** [comment]
that was all i was waiting for 7icon that is all i will any more request.

**Comment by krisu5** [comment]
Doesn't have Aegis-supported 2FA: https://www.onlinesbi.com/sbijava/mobile/sbsecure_otp_app_faq.html
