### ISSUE TITLE
Update icon: Pixelfed

### ISSUE THREAD

**Issue by holequantum** [aegis-icons/aegis-icons#639]
### URL for the brand / site / app

https://pixelfed.org/ & https://pixelfed.social/

### Logo resources for the icon

https://pixelfed.nyc3.digitaloceanspaces.com/logos/pixelfed-icon-color.svg

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines).

**Comment by holequantum** [comment]
make it update icon by mistake it become new Icon

**Comment by krisu5** [comment]
Seriously, search the icon pack / site first before making any issues: https://aegis-icons.github.io/

Already exists.

**Comment by krisu5** [comment]
> make it update icon by mistake it become new Icon

There's no need for update either.
