### ISSUE TITLE
Icon request: Endeavouros

### ISSUE THREAD

**Issue by holequantum** [aegis-icons/aegis-icons#647]
### URL for the brand / site / app

https://endeavouros.com/

### Logo resources for the icon

https://github.com/endeavouros-team/endeavouros-theming/blob/master/endeavouros.svg

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines).

**Comment by krisu5** [comment]
Couldn't found anything in Google that this has 2FA.

**Comment by holequantum** [comment]
![Screenshot from 2022-08-19 14-27-43](https://user-images.githubusercontent.com/108695843/185583914-30253731-cebb-464f-af40-82960b689d3e.png)
![Screenshot from 2022-08-19 14-27-52](https://user-images.githubusercontent.com/108695843/185583922-03e2367d-e066-4b54-b270-878e403347cf.png)
why did you just closed my request without asking just ask me i will provide you details
i understand that you only add icon which have 2fa support so i request only those which have support. kindly reopen this. thanks.

**Comment by krisu5** [comment]
Thanks for the info (you need to be more specific about if it's forum), but:

[We only make icons for really popular forums](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#case-by-case-basis) (at least over 250,000 total members and high posting activity). This forum only has 5909 members. For forums under the requirements, forum software related icons are the prefer solution.

Use one of the **Discourse** icon.

**Comment by holequantum** [comment]
yes but it is a new project and it is currently growing as a alternative arch base distro hence having it will not make anything wrong...
anyways thanks.
