### ISSUE TITLE
Icon request: F-Droid

### ISSUE THREAD

**Issue by holequantum** [aegis-icons/aegis-icons#650]
### URL for the brand / site / app

https://forum.f-droid.org/

### Logo resources for the icon

https://gitlab.com/fdroid/fdroidclient/-/blob/master/logo-icon.svg

### Anything else?

A very well known android store apps.

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines).

**Comment by krisu5** [comment]
[We only make icons for really popular forums](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#case-by-case-basis) (at least over 250,000 total members and high posting activity). This forum only has [6211](https://forum.f-droid.org/u?order=likes_received) members. For forums under the requirements, forum software related icons are the prefer solution.

Use one of the**Discourse** icons.

---

In the Discourse based forums, you can find the user count by: hamburger menu (top-right) -> "Users" -> user count is next to "filter by username".
