### ISSUE TITLE
Icon request: BitGo

### ISSUE THREAD

**Issue by CyberMageIL** [aegis-icons/aegis-icons#66]
- URL of the site or app: https://www.bitgo.com/
- Logo resources for the icon: Attached self-made icon (png + svg), feel free to edit as you please :)
(Original logo vector was taken from: http://logovectorseek.com/bitgo-logo-vector-svg/)

[BitGo Icon.zip](https://github.com/krisu5/aegis-icons/files/4545954/BitGo.Icon.zip)

**Comment by krisu5** [comment]
Here you go:

https://github.com/krisu5/aegis-icons/blob/master/PNG/BitGo.png
