### ISSUE TITLE
Icon request: Battle.net

### ISSUE THREAD

**Issue by DerBraky** [aegis-icons/aegis-icons#67]
- URL of the site or app **(required):** https://battle.net/
- Logo resources for the icon **(optional, but recommended):** https://www.dropbox.com/s/148sfcn76ipwqje/Battlenet.svg?dl=0

**Comment by krisu5** [comment]
Use Blizzard icon (Blizzard has rebranded the Battle.net to ["Blizzard Battle.net"](https://en.wikipedia.org/wiki/Battle.net#Rebranding))

https://github.com/krisu5/aegis-icons/blob/master/PNG/Blizzard.png
