### ISSUE TITLE
Icon Request: signrequest.com

### ISSUE THREAD

**Issue by XrtX** [aegis-icons/aegis-icons#674]
URL for the brand / site / app

https://www.signrequest.com/

Logo resources for the icon

https://www.signrequest.com/

No response
Anything else?

2FA Proof:
https://help.signrequest.com/hc/en-us/articles/360004932594-Enable-Two-Factor-Authentication-

I have read and followed the issue guidelines.

**Comment by krisu5** [comment]
Don't bypass the issue closing by using empty issue.
