### ISSUE TITLE
Icon request: WEB.DE

### ISSUE THREAD

**Issue by DerBraky** [aegis-icons/aegis-icons#68]
- URL of the site or app **(required):** https://web.de/
- Logo resources for the icon **(optional, but recommended):** https://www.dropbox.com/s/2qqwz0cfyvxbyfn/WEBDE.svg?dl=0

**Comment by krisu5** [comment]
Here you go:

https://github.com/krisu5/aegis-icons/blob/master/PNG/WEB.DE.png
Black logo variation: https://github.com/krisu5/aegis-icons/blob/master/PNG/Variations/WEB.DE%20fg.var.png
