### ISSUE TITLE
Icon request: SumoLogic

### ISSUE THREAD

**Issue by benwaffle** [aegis-icons/aegis-icons#7]
https://www.sumologic.com/

**Comment by krisu5** [comment]
SVG logo: https://www.sumologic.com/img/logo.svg

**Comment by benwaffle** [comment]
They also use this, I think it would fit better
![image](https://user-images.githubusercontent.com/1713819/64929695-22aa7080-d7f7-11e9-8b1f-b6c7c239fe1f.png)

**Comment by krisu5** [comment]
Yeah, I noticed that variation too, but there's no SVG version of that, so I still had to use SVG that I linked and recreate it.

Anyway, here it is. https://github.com/krisu5/aegis-icons/blob/master/PNG/SumoLogic.png
