### ISSUE TITLE
Icon request: BitDefender

### ISSUE THREAD

**Issue by AbramTTP** [aegis-icons/aegis-icons#71]
- URL of the site or app https://www.bitdefender.com/
- Logo resources for the icon https://pbs.twimg.com/profile_images/1228219239808417794/65vjbHgf_400x400.png

**Comment by AbramTTP** [comment]
![BitDefender](https://user-images.githubusercontent.com/7013007/80700443-5630d580-8b10-11ea-91e4-258731578076.png)

What I manage to come up with based on 1024x1024 resolution

**Comment by krisu5** [comment]
Seems okay, but logo size is too big (comparing to the template) and color is bit muted.

Here's mine: https://github.com/krisu5/aegis-icons/blob/master/PNG/Bitdefender.png

**Comment by AbramTTP** [comment]
Ah yes, indeed muted a little, should have looked at the official site again. The final version is awesome!
