### ISSUE TITLE
Icon request: DocuSign

### ISSUE THREAD

**Issue by AbramTTP** [aegis-icons/aegis-icons#72]
- URL of the site or app **(required):** https://www.docusign.com/
- Logo resources for the icon **(optional, but recommended):** https://www.underconsideration.com/brandnew/archives/new_logo_for_docusign.php

**Comment by AbramTTP** [comment]
![Logo_Template](https://user-images.githubusercontent.com/7013007/80700454-592bc600-8b10-11ea-889a-37d01d290107.png)

What I manage to come up with based on 1024x1024 resolution (If white circular background)

**Comment by krisu5** [comment]
Never use white as background, white always goes to logo (with few exceptions).

DocuSign is in the [todo list](https://github.com/krisu5/aegis-icons/projects/1), but they have really [problematic terms for using trademarks](https://www.docusign.com/IP/trademark-license). Basically I have to ask permission from them. I could ignore and make it still, SimpleIcons.org has done that.

**Comment by AbramTTP** [comment]
Good to hear from you. That is an excellent site for svg logo, shall bookmark that.

Noted on the issue you are facing, and the color.

Shortly I will have an Illustrator ai file for G2A game store.

**Comment by AbramTTP** [comment]
Do you happen to have a template for anyone who also wishes to submit their own icon for your approval (we will just follow your style all the way)?

As I place the logo in the circle sometimes I am not sure about the right size. I am more familiar with Photoshop than Illustrator but I can take both file templates (while practicing on Illustrator)

**Comment by AbramTTP** [comment]
![DocuSign](https://user-images.githubusercontent.com/7013007/80708996-29d08580-8b1f-11ea-8a79-ed8fbbe26c3d.png)

Update: What I come up for myself at the moment until your official version is released.

**Comment by krisu5** [comment]
> Do you happen to have a template for anyone who also wishes to submit their own icon for your approval (we will just follow your style all the way)?

Since you're using Illustrator, you can use "ai_icon_template.ait" (it's Illustrator template file). The guides you see there, you don't have to follow them 100%. In wider logos it's acceptable to cross the guides (see [Bitstamp.ai](https://github.com/krisu5/aegis-icons/blob/master/AI/Bitstamp.ai)). Important thing is the correct colors and that logo is embed into the AI file, not linked.

Contributing process is still WIP, I have make documents and SVG template for that too.

But I'm putting this on hold, because I have to ask permission for trademark usage.

**Comment by krisu5** [comment]
Sorry for long delay. :/

I finally sended email about two weeks ago, 3 times even. No single response. So screw it, I made the icons anyway. If they don't like it, I have the [info on take downs right here](https://github.com/krisu5/aegis-icons#disclaimer).

Here's the icons.
https://github.com/krisu5/aegis-icons/blob/master/PNG/DocuSign.png
https://github.com/krisu5/aegis-icons/blob/master/PNG/Variations/DocuSign%20bg.var.png
