### ISSUE TITLE
Icon request: G2A

### ISSUE THREAD

**Issue by AbramTTP** [aegis-icons/aegis-icons#73]
- URL of the site or app **(required):** https://www.g2a.com/
- Logo resources for the icon **(optional, but recommended):** https://worldvectorlogo.com/logo/logo-g2a-icon

**Comment by AbramTTP** [comment]
![G2A](https://user-images.githubusercontent.com/7013007/80707454-90a06f80-8b1c-11ea-81b5-18491ff7f95f.png)

Github doesn't support .ai/.svg
This is what I exported out of Adobe Illustrator

**Comment by krisu5** [comment]
> Github doesn't support .ai/.svg
> This is what I exported out of Adobe Illustrator

Upload as ZIP folder, that will work.

**Comment by AbramTTP** [comment]
[G2A.zip](https://github.com/krisu5/aegis-icons/files/4558331/G2A.zip)

You're right, didn't see .zip in the list of supported formats.

I am using older Illustrator CS6, but it should work. In this .zip contains G2A's .ait and .svg files.

My main portfolio is not exactly Digital Artist or Designer, after all. I was specializing in Computer Graphics but now I am more into System Security

Thank you!

**Comment by krisu5** [comment]
I had to make changes, because you don't need to (and shouldn't) save over the template file. 😛 
AI is format for saving the actual artwork. But I got the icon still, that's main point.

Icon URL for just in case: https://github.com/krisu5/aegis-icons/blob/master/PNG/G2A.png
