### ISSUE TITLE
Icon request: Prey (Device Security)

### ISSUE THREAD

**Issue by AbramTTP** [aegis-icons/aegis-icons#74]
- URL of the site or app **(required):** https://preyproject.com/
- Logo resources for the icon **(optional, but recommended):** https://www.compsmag.com/wp-content/uploads/2018/08/1535169987_680_600x600bb-1024x1024.jpg

(The background should be the blue color they often use on website)

**Comment by AbramTTP** [comment]
![PreyProject](https://user-images.githubusercontent.com/7013007/80705133-749acf00-8b18-11ea-93cb-0e63c4d21156.png)

Here is what I manage to create.

**Comment by krisu5** [comment]
Here's mine: https://github.com/krisu5/aegis-icons/blob/master/PNG/Prey.png

(vector at the website is different, most likely updated version of the logo)

**Comment by AbramTTP** [comment]
Amazing! Thanks (and to all other requests I opened that are closed)
