### ISSUE TITLE
Icon request: Register.ly

### ISSUE THREAD

**Issue by ghost** [aegis-icons/aegis-icons#746]
### URL for the brand / site / app

https://register.ly/

### Logo resources for the icon

https://register.ly/about/brand/

### Proof of the Aegis-compatible 2FA

https://register.ly/two-factor-authentication-register-ly

### Anything else?

Register.ly is a web host for .ly domains.

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.

**Comment by krisu5** [comment]
Can't access the PDF vectors, they block the access. I contact them about it yesterday.

If they don't answer / do nothing, then I have to unfortunately reject this, because the raster images of the logo are too small for image tracing and couldn't find better source.

**Comment by ghost** [comment]
Okay, thanks for looking into it. If they don't get back to you, I'm also happy to reach out as a paying customer to see if they would respond. 

What specifically should I request from them - PDF vectors of their logo?

**Comment by krisu5** [comment]
> What specifically should I request from them - PDF vectors of their logo?

Yes, also SVG and EPS are OK too. Basically any common vector format.

Or ask them to disable the firewall blocking of the "download" / "PDF" links from the https://register.ly/about/brand/ page 😅

**Comment by krisu5** [comment]
I got no response for my messages and nothing was changed for the download links, but I tried image tracing anyways and it got good results despite the low resolution. So, here's the icon.

I *might* fix the icon later with official vector, if they decide to answer me (unlikely tbh) or fix their download links for vectors.

https://github.com/aegis-icons/aegis-icons/blob/master/icons/1_Primary/Register.ly.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
