### ISSUE TITLE
Icon requests: DeGiro, OwnCube, YoYo Games, Star Citizen and Alternative for NextCloud 

### ISSUE THREAD

**Issue by tdoerrich** [aegis-icons/aegis-icons#78]
- DeGiro: https://trader.degiro.nl/login/de/#/login
- OwnCube: https://owncube.com/index_de.php
- YoYo Games, Game Maker: https://www.yoyogames.com/
- Star Citizen: https://robertsspaceindustries.com/star-citizen
- Alternative icon for NextCloud (I have two different accounts and would love another background color for an alternative icon if possible): https://nextcloud.com/

## Icons
DeGiro: http://www.degiro.nl/data/pdf/DEGIRO_press_kit.zip
![DEGIRO_Logo2018](https://user-images.githubusercontent.com/5912371/81046572-fabc6a00-8eb8-11ea-807e-57e1a9da0021.png)

OwnCube: Sadly couldn't find a logo to download

YoYo Games: http://coal.yoyogames.com/brand/Brand_Logos.zip
![YoYoGames_Primary_Transparent](https://user-images.githubusercontent.com/5912371/81046838-80401a00-8eb9-11ea-9849-10dc1d1e24b2.png)

Star Citizen: https://dto9r5vaiz7bu.cloudfront.net/6uckky48kzfp0/source.png

**Comment by krisu5** [comment]
> Alternative icon for NextCloud (I have two different accounts and would love another background color for an alternative icon if possible): https://nextcloud.com/

BG variations are only made for icons that has dark background in the original icon, for dark / AMOLED theme users.

I can make generic cloud icon though if that's okay.

**Comment by tdoerrich** [comment]
> I can make generic cloud icon though if that's okay.

Yeah, that would also be awesome! :) Just want something different to see on the image which account is which. :)

**Comment by krisu5** [comment]
Here you go:

https://github.com/krisu5/aegis-icons/blob/master/PNG/DEGIRO.png
https://github.com/krisu5/aegis-icons/blob/master/PNG/OwnCube.png
https://github.com/krisu5/aegis-icons/blob/master/PNG/Star%20Citizen.png
https://github.com/krisu5/aegis-icons/blob/master/PNG/Variations/Star%20Citizen%20bg.var.png (BG variation)
https://github.com/krisu5/aegis-icons/blob/master/PNG/YoYo%20Games.png
https://github.com/krisu5/aegis-icons/blob/master/PNG/Generic%20Icons/Cloud.png

Also, if you really want NextCloud icon with different background, you could download the NextCloud SVG, edit it with [Vectr](https://vectr.com/) webapp and export as 1024px x 1024px PNG. I'm making tutorial for that soonish.

**Comment by tdoerrich** [comment]
Thank you!
