### ISSUE TITLE
Icon request: Atlassian

### ISSUE THREAD

**Issue by Otiel** [aegis-icons/aegis-icons#79]
- URL of the site or app: https://www.atlassian.com
- Logo resources for the icon: https://wac-cdn.atlassian.com/dam/jcr:616e6748-ad8c-48d9-ae93-e49019ed5259/Atlassian-horizontal-blue-rgb.svg
- [svg.zip](https://github.com/krisu5/aegis-icons/files/4592130/svg.zip)

![Atlassian](https://user-images.githubusercontent.com/3851902/81279627-adc2ca00-9057-11ea-9eb4-30c17ad178a2.png)

**Comment by krisu5** [comment]
Done: https://github.com/krisu5/aegis-icons/blob/master/PNG/Atlassian.png

**Comment by Otiel** [comment]
Thanks, that was quick!
