### ISSUE TITLE
Icon request: VK

### ISSUE THREAD

**Issue by Leopold702** [aegis-icons/aegis-icons#80]
Would be nice if you add icon for VK - Russian social network.

- URL of the site or app **(required):** https://vk.com/
- Logo resources for the icon **(optional, but recommended):** https://vk.com/brand (there is a switch to English at the bottom of the page in case page opens in Russian)

**Comment by krisu5** [comment]
Here you go:

https://github.com/krisu5/aegis-icons/blob/master/PNG/VK.png

**Comment by Leopold702** [comment]
Thank you for such a fast response and great icon, really appreciate that.
