### ISSUE TITLE
Icon request: orcid.org

### ISSUE THREAD

**Issue by Jonas1312** [aegis-icons/aegis-icons#81]
- URL of the site or app **(required):** https://orcid.org/
- Logo resources for the icon **(optional, but recommended):** https://orcid.org/trademark-and-id-display-guidelines

**Comment by krisu5** [comment]
Here you go:

https://github.com/krisu5/aegis-icons/blob/master/PNG/ORCID.png

**Comment by Jonas1312** [comment]
thanks!
