### ISSUE TITLE
Icon request: Surfshark

### ISSUE THREAD

**Issue by brunopereira7** [aegis-icons/aegis-icons#82]
Remember to add **name of the site or app** at the end of the title (you can delete this line if you want)

- URL of the site or app **(required):** https://surfshark.com/
- Logo resources for the icon **(optional, but recommended):** https://surfshark.com/press#media-assets

**Comment by krisu5** [comment]
Done: https://github.com/krisu5/aegis-icons/blob/master/PNG/Surfshark.png

**Comment by brunopereira7** [comment]
Thank you
