### ISSUE TITLE
Icon request: Wealthsimple

### ISSUE THREAD

**Issue by A37stKpDodi4BEr65TXb** [aegis-icons/aegis-icons#83]
- URL of the site or app: https://www.wealthsimple.com/en-ca/
- Logo resources for the icon: [Facebook profile pic](https://scontent.fyzd1-3.fna.fbcdn.net/v/t31.0-8/12182826_485456331616404_710773929082544915_o.jpg?_nc_cat=1&_nc_sid=09cbfe&_nc_ohc=x0rYhbLrU2AAX8FpfCi&_nc_ht=scontent.fyzd1-3.fna&oh=6218772b0ea1536a42bbfe4182565741&oe=5EF586D5)

**Comment by krisu5** [comment]
Vector: https://www.wealthsimple.com/static/ws-wordmark-7a6a6ea384e8586aaeb2597547f86158.svg

Colors: https://wealthsimple-grow.ghost.io/content/images/2015/11/brand_assets-2.png

**Comment by krisu5** [comment]
Here you go:

https://github.com/krisu5/aegis-icons/blob/master/PNG/Wealthsimple.png
