### ISSUE TITLE
Icon request: Hack The Box

### ISSUE THREAD

**Issue by GambogeGoose** [aegis-icons/aegis-icons#86]
- URL of the site or app **(required):** [Hack The Box](https://www.hackthebox.eu/)
- Logo resources for the icon **(optional, but recommended):** [Logo](https://www.hackthebox.eu/images/favicon.png)

**Comment by krisu5** [comment]
Here you go!

https://github.com/krisu5/aegis-icons/blob/master/PNG/Hack%20The%20Box.png
