### ISSUE TITLE
Icon request: Contabo

### ISSUE THREAD

**Issue by GambogeGoose** [aegis-icons/aegis-icons#87]
- URL of the site or app **(required):** [Contabo](https://contabo.com/)
- Logo resources for the icon **(optional, but recommended):** [Logo](https://contabo.com/blog/wp-content/uploads/2020/02/contabo.svg)

**Comment by krisu5** [comment]
Here you go!

https://github.com/krisu5/aegis-icons/blob/master/PNG/Contabo.png
