### ISSUE TITLE
Icon request: UNMS

### ISSUE THREAD

**Issue by techwithjake** [aegis-icons/aegis-icons#90]
- URL of the site or app **(required):** https://unms.com/
- Logo resources for the icon **(optional, but recommended):** https://unms.com/assets/images/icon-74a3f.svg

I will try to make it myself but I am no good with Inkscape and the likes. But I will try as well to get this request filled myself.

**Comment by krisu5** [comment]
OK :)

I updated the comment with actual site URL.

Also, I think **Ubiquiti** is better name for icon, because that's the actual brand and product logo isn't different from the brand logo.

**Comment by krisu5** [comment]
I think I misunderstood, I though you're gonna make the icon. Sorry for delay. 😅

https://github.com/krisu5/aegis-icons/blob/master/PNG/Ubiquiti.png

**Comment by techwithjake** [comment]
No worries. I tried and utterly failed. Thanks for making it!
