### ISSUE TITLE
Icon request: Local Monero

### ISSUE THREAD

**Issue by GambogeGoose** [aegis-icons/aegis-icons#91]
- URL of the site or app **(required):** [Local Monero](http://localmonero.co/)
- Logo resources for the icon **(optional, but recommended):** [Logo](https://revuo-monero.com/img/localmonero-logo.png)

**Comment by krisu5** [comment]
My issue is with the logo: it's almost exactly the same as Monero currency icon. Only major difference is background color.

I would rather make a generic icon for Monero currency.

**Comment by krisu5** [comment]
I made generic icon for Monero.

https://github.com/krisu5/aegis-icons/blob/master/PNG/Generic/Monero.png
