### ISSUE TITLE
Icon request: Warner Bros Games

### ISSUE THREAD

**Issue by juanico10** [aegis-icons/aegis-icons#913]
### URL for the brand / site / app

https://warnerbrosgames.com/

### Logo resources for the icon

https://upload.wikimedia.org/wikipedia/commons/5/58/Warner_Bros._Games.svg

### Proof of the Aegis-compatible 2FA

Attached is the [url](https://help.askcustomercare.warnerbros.com/hc/en-us/articles/360002063768-Multi-Factor-Authentication-MFA-for-ASK) where Warner Bross explains where the 2fa is performed.

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.

**Comment by krisu5** [comment]
Already exists. Please use search on our [website](https://aegis-icons.github.io/) before submitting any issues.
