### ISSUE TITLE
Icon request: CrowdNode

### ISSUE THREAD

**Issue by eloyesp** [aegis-icons/aegis-icons#927]
### URL for the brand / site / app

https://crowdnode.io/

### Proof of the Aegis-compatible 2FA

The 2FA is enforced (see: https://knowledge.crowdnode.io/en/articles/2224647-can-i-avoid-having-two-factor-authentication-enabled) and it is using TOTP as can be seen here: https://knowledge.crowdnode.io/en/articles/2948497-i-have-problems-with-setting-up-the-two-factor-authentication-2fa-mfa-on-auth0-what-can-i-do

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.

**Comment by krisu5** [comment]
Please use correct capitalization for issue title, as mentioned on the issue form. All three of your issues had wrong capitalization in the title.

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/icons/1_Primary/CrowdNode.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
