### ISSUE TITLE
🎉 Good news! Inserting icons to Aegis will be easier at the future.

### ISSUE THREAD

**Issue by krisu5** [aegis-icons/aegis-icons#93]
See here: https://github.com/beemdevelopment/Aegis/issues/509

**Comment by ciotorcristian** [comment]
Any updates on this?

**Comment by krisu5** [comment]
Not much, here's draft pull request related to it: https://github.com/beemdevelopment/Aegis/pull/539

**Comment by krisu5** [comment]
Okay, lot has happen lately, but finally there's [beta version of Aegis that supports icon packs](https://github.com/beemdevelopment/Aegis/releases/tag/v2.0-beta1).

You can test the beta version with aegis-icons's ~~[pre-release pack](https://github.com/aegis-icons/aegis-icons/releases/tag/2021-04-10)~~ (there's also [icon pack](https://github.com/alexbakker/aegis-simple-icons/releases) by Aegis dev Alex, that automatically makes icons from [Simple Icons's](https://simpleicons.org/) logos/colors).

**Comment by krisu5** [comment]
Aegis v2.0 is out of beta and available at [Play Store](https://play.google.com/store/apps/details?id=com.beemdevelopment.aegis) and [Github](https://github.com/beemdevelopment/Aegis/releases/tag/v2.0). F-Droid version isn't up yet as of writing this.

First proper icon pack release can be found here: https://github.com/aegis-icons/aegis-icons/releases/tag/2021-05-24
