### ISSUE TITLE
Icon request: Cisco, EA, Parsec, Samsung, Green

### ISSUE THREAD

**Issue by ciotorcristian** [aegis-icons/aegis-icons#98]
- Cisco : https://www.cisco.com/
- Electronic arts: https://www.ea.com/
- Parsec: https://parsecgaming.com/
- Samsung: https://www.samsung.com/
- Green: https://blockstream.com/green/

- Logo resources for the icon :
https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/Cisco_logo.svg/1024px-Cisco_logo.svg.png
https://logos-download.com/wp-content/uploads/2016/11/EA_logo_Electronic_Arts.png
https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcR4mgtBJBSnbWN7GqRZF64vuBBufceTEMY5RA&usqp=CAU
https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Samsung_Logo.svg/1024px-Samsung_Logo.svg.png
https://walletscrutiny.com/images/wallet_icons/com.greenaddress.greenbits_android_wallet.png

**Comment by krisu5** [comment]
Blockstream Green SVG: https://github.com/Blockstream/green_qt/blob/master/assets/svg/home.svg

**Comment by krisu5** [comment]
Here you go!

https://github.com/krisu5/aegis-icons/blob/master/PNG/Blockstream%20Green.png
https://github.com/krisu5/aegis-icons/blob/master/PNG/Cisco.png
https://github.com/krisu5/aegis-icons/blob/master/PNG/Electronic%20Arts.png
https://github.com/krisu5/aegis-icons/blob/master/PNG/Parsec.png
https://github.com/krisu5/aegis-icons/blob/master/PNG/Samsung.png
